// ── English Question Bank ─────────────────────────────────────

function getEnglishQuestions(level) {
  const banks = { reception: qReception, year1: qYear1, year2: qYear2,
    year3: qYear3, year4: qYear4, year5: qYear5, year6: qYear6 };
  return (banks[level] || banks.year1)();
}

function mcq(q, correct, w1, w2, w3, emoji, explanation) {
  const answers = sh([correct, w1, w2, w3]);
  return { question: q, answers, correct: answers.indexOf(correct),
           emoji: emoji || null, explanation: explanation || null };
}
function typed(q, answer, accepted, emoji, explanation) {
  return { question: q, type:'typed', answers:[answer], correct:0,
    acceptedAnswers: accepted || [answer.toLowerCase()],
    emoji: emoji || null, explanation: explanation || null };
}
function sh(a) { for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a; }

function qReception() { return [
  // ── Starting sounds ──
  mcq('Which letter starts the word "Apple"?','A','B','C','D','🍎',
    '"Apple" — say it slowly: A-pple! The first sound is "A"!'),
  mcq('Which letter starts "Ball"?','B','P','D','R','⚽',
    '"Ball" — say it: B-all! The first sound is "B"!'),
  mcq('Which letter starts "Cat"?','C','K','G','S','🐱',
    '"Cat" — say it: C-at! The first sound is "C"!'),
  mcq('Which letter starts "Dog"?','D','B','P','T','🐶',
    '"Dog" — say it: D-og! The first sound is "D"!'),
  mcq('Which letter starts "Egg"?','E','A','I','O','🥚',
    '"Egg" — say it: E-gg! The first sound is "E"!'),
  mcq('Which letter starts "Fish"?','F','V','P','B','🐟',
    '"Fish" — say it: F-ish! The first sound is "F"!'),
  mcq('Which letter starts "Hat"?','H','A','Y','W','🎩',
    '"Hat" — say it: H-at! The first sound is "H"!'),
  mcq('Which letter starts "Jam"?','J','G','Y','D','🍓',
    '"Jam" — say it: J-am! The first sound is "J"!'),
  mcq('Which letter starts "Kite"?','K','C','G','Q','🪁',
    '"Kite" — say it: K-ite! The first sound is "K"!'),
  mcq('Which letter starts "Lion"?','L','R','N','M','🦁',
    '"Lion" — say it: L-ion! The first sound is "L"!'),
  mcq('Which letter starts "Moon"?','M','N','W','B','🌙',
    '"Moon" — say it: M-oon! The first sound is "M"!'),
  mcq('Which letter starts "Sun"?','S','C','Z','X','☀️',
    '"Sun" — say it: S-un! The first sound is "S"!'),
  // ── Rhyming words ──
  mcq('Which word rhymes with "hat"?','cat','dog','big','run',null,
    '"Hat" and "cat" both end in "-at"! Rhyming words share the same ending!'),
  mcq('Which word rhymes with "big"?','pig','hat','cup','dog',null,
    '"Big" and "pig" both end in "-ig"! Listen for the same ending sound!'),
  mcq('Which word rhymes with "sun"?','run','cat','big','hop',null,
    '"Sun" and "run" both end in "-un"! They rhyme!'),
  mcq('Which word rhymes with "cake"?','lake','sock','bird','tree',null,
    '"Cake" and "lake" both end in "-ake"! They rhyme!'),
  mcq('Which word rhymes with "bed"?','red','cup','dog','fish',null,
    '"Bed" and "red" both end in "-ed"! They rhyme!'),
  mcq('Which word rhymes with "hop"?','top','cat','pig','sun',null,
    '"Hop" and "top" both end in "-op"! They rhyme!'),
  mcq('Which word rhymes with "night"?','light','moon','star','dark',null,
    '"Night" and "light" both end in "-ight"! They rhyme!'),
  // ── Word categories ──
  mcq('Which is a colour?','red','cat','run','big',null,
    'Red is a colour you can see! "cat" is an animal, "run" is an action!'),
  mcq('Which is a colour?','blue','jump','dog','five',null,
    'Blue is a colour — like the sky! "jump" is a doing word, "dog" is an animal!'),
  mcq('Which word is a number?','three','blue','jump','funny',null,
    '"three" is the word for the number 3! Blue is a colour, jump is an action!'),
  mcq('Pick the animal word:','rabbit','table','happy','green',null,
    'A rabbit is a fluffy animal! "table" is furniture, "happy" is a feeling!'),
  mcq('Which word is an animal?','horse','purple','sit','cold',null,
    'A horse is a big animal! "purple" is a colour, "sit" is a doing word!'),
  mcq('Which is NOT an animal?','chair','cat','dog','fish','🪑',
    'A chair is furniture — something you sit on! Cats, dogs, and fish are all animals!'),
  // ── Counting letters ──
  mcq('How many letters in "dog"?','3','2','4','5',null,
    '"dog" has 3 letters: D-O-G! Count each letter carefully!'),
  mcq('How many letters in "fish"?','4','3','5','2',null,
    '"fish" has 4 letters: F-I-S-H! Count each letter one by one!'),
  mcq('How many letters in "cat"?','3','2','4','5','🐱',
    '"cat" has 3 letters: C-A-T! Count them: C…A…T — three!'),
  mcq('How many letters in "sun"?','3','4','2','5','☀️',
    '"sun" has 3 letters: S-U-N!'),
  // ── Vowels and consonants ──
  mcq('Which letter is a vowel?','A','B','C','D',null,
    'The vowels are A, E, I, O, U! B, C, D are all consonants!'),
  mcq('Which letter is a vowel?','E','F','G','H',null,
    'E is a vowel! The vowels are A, E, I, O, U — everything else is a consonant!'),
  mcq('Which letter is a vowel?','O','P','Q','R',null,
    'O is a vowel! Remember: A, E, I, O, U are the five vowels!'),
  mcq('Which letter is NOT a vowel?','B','A','E','I',null,
    'B is a consonant, not a vowel! The vowels are A, E, I, O, U!'),
  mcq('How many vowels are in "cat"?','1','2','3','0',null,
    '"cat" — C is a consonant, A is a vowel, T is a consonant. Just 1 vowel!'),
  mcq('How many vowels are in "boat"?','2','1','3','0',null,
    '"boat" — b(consonant), o(vowel), a(vowel), t(consonant). Two vowels: O and A!'),
  // ── Basic vocabulary ──
  mcq('"The sun is ___." Pick the correct word:','bright','quickly','under','and',null,
    '"Bright" describes what the sun looks like — it\'s an adjective (describing word)!'),
  mcq('Which word is a verb (doing word)?','jump','table','happy','sky',null,
    'A verb is a doing word! "jump" is something you DO — you can jump!'),
  mcq('Which word means the opposite of big?','small','tall','fast','cold',null,
    'Big and small are opposites — they mean completely different sizes!'),
  mcq('Which letter makes the "s" sound?','S','C','Z','X',null,
    'The letter S makes the "s" sound — like in "snake" and "sun"!'),
  mcq('Which word means the opposite of hot?','cold','warm','cool','bright',null,
    'Hot and cold are opposites! On a cold day you wear a coat!'),
  mcq('Which word means happy?','glad','sad','angry','tired',null,
    '"Glad" means happy! Sad is the opposite of happy!'),
  mcq('Which is a shape?','circle','rabbit','red','run','🔵',
    'A circle is a round shape! Rabbit is an animal, red is a colour!'),
  typed('What sound does the letter "B" make? Type the letter:','b',['b'],'🅱️',
    'The letter B makes a "buh" sound — like in "ball", "boat", and "bird"!'),
  typed('What letter starts the word "sun"?','s',['s'],'☀️',
    '"Sun" starts with the letter S! S makes a "sss" sound!'),
  typed('What letter starts the word "frog"?','f',['f'],'🐸',
    '"Frog" starts with the letter F! F makes a "fff" sound!'),
];}

function qYear1() { return [
  // ── Typed spelling (CVC and simple words) ──
  typed('Spell the word for this animal: 🐶','dog',['dog'],null,
    'Dog is spelled D-O-G! A dog is a friendly pet that barks!'),
  typed('Spell the word for this animal: 🐱','cat',['cat'],null,
    'Cat is spelled C-A-T! A cat is a pet that meows!'),
  typed('Spell the word for this fruit: 🍎','apple',['apple'],null,
    'Apple is spelled A-P-P-L-E! Remember: it has double P in the middle!'),
  typed('Spell the word for this vehicle: 🚗','car',['car'],null,
    'Car is spelled C-A-R! Three letters: C, A, R!'),
  typed('Spell the word for where we live:','home',['home'],null,
    'Home is spelled H-O-M-E! It ends with a silent E!'),
  // ── Spelling MCQ ──
  mcq('Which is spelled correctly?','friend','frend','freind','frind',null,
    '"friend" — F-R-I-E-N-D. The tricky bit is "ie" not "ei"!'),
  mcq('Pick the correct spelling:','come','kom','kome','cume',null,
    '"come" is a tricky word — it ends in a silent "e"!'),
  mcq('Correct spelling:','said','sed','sayd','saed',null,
    '"said" is a tricky word — S-A-I-D! The "ai" makes an "e" sound!'),
  mcq('Correct spelling:','they','thay','thei','tey',null,
    '"they" is spelled T-H-E-Y! The "ey" at the end makes an "ee" sound!'),
  mcq('Correct spelling:','was','wuz','wos','waz',null,
    '"was" is spelled W-A-S! It\'s a tricky word because it sounds like "woz"!'),
  mcq('Correct spelling:','little','littel','litle','littul',null,
    '"little" is spelled L-I-T-T-L-E! Double T in the middle!'),
  mcq('Correct spelling:','have','hav','haiv','haev',null,
    '"have" — H-A-V-E. It ends in a silent E!'),
  mcq('Correct spelling:','once','wonce','onse','ownce',null,
    '"once" — O-N-C-E. It sounds like "wunce" but is spelled with an O!'),
  mcq('Correct spelling:','love','luv','lov','loov',null,
    '"love" — L-O-V-E. The O makes an "u" sound — tricky!'),
  mcq('Correct spelling:','school','skool','scool','skcool',null,
    '"school" — S-C-H-O-O-L. The "sch" makes a "sk" sound!'),
  // ── Word meanings / synonyms ──
  mcq('Which word means "happy"?','glad','sad','angry','tired',null,
    '"Glad" means happy or pleased! Sad is the opposite of happy!'),
  mcq('Which word means "big"?','large','tiny','short','soft',null,
    '"Large" means big! Tiny means the opposite — very small!'),
  mcq('Which word means "fast"?','quick','slow','quiet','dark',null,
    '"Quick" means fast! Slow is the opposite of fast!'),
  // ── Nouns / Verbs / Adjectives ──
  mcq('Which word is a noun (naming word)?','table','run','big','slowly',null,
    'A noun is a naming word — "table" is a thing you can touch!'),
  mcq('The dog ___ loudly. Pick the verb:','barked','quickly','big','and',null,
    '"barked" is the doing word — the dog DID the barking!'),
  mcq('"She is ___ the book." Choose:','reading','run','happy','quick',null,
    '"She is reading the book" — reading is the verb (doing word) here!'),
  mcq('Which word is an adjective?','fluffy','jump','slowly','the',null,
    'An adjective describes a noun! "fluffy" describes what something feels like!'),
  mcq('Which is a noun?','chair','run','tall','gently',null,
    '"chair" is a noun — a naming word for a thing you sit on!'),
  mcq('Which word is a verb?','swim','big','red','book','🏊',
    '"swim" is a doing word — something you DO!'),
  mcq('Which word is an adjective?','tiny','jump','table','quickly',null,
    '"tiny" describes how small something is — it\'s a describing word (adjective)!'),
  // ── Sentence punctuation ──
  mcq('Which sentence has correct punctuation?',
    'The cat sat on the mat.','the cat sat on the mat','The cat sat on the mat','the Cat sat',null,
    'Sentences start with a CAPITAL letter and end with a full stop (.)!'),
  mcq('Which sentence is correct?',
    'My dog is brown.','my dog is brown.','My Dog Is Brown','my Dog is brown',null,
    'Start with a capital M, end with a full stop. Only names use capital letters in the middle!'),
  mcq('What goes at the end of a question?','?','.',',','!',null,
    'Questions end with a question mark (?) — it shows you\'re asking something!'),
  mcq('What goes at the end of "What a great day"?','!','.',',','?',null,
    'An exclamation mark (!) shows excitement or surprise — "What a great day!"'),
  // ── Opposites ──
  mcq('Opposite of "day"?','night','sun','hot','light',null,
    'Day and night are opposites — day has sunlight, night has darkness!'),
  mcq('Opposite of "hot"?','cold','warm','cool','mild',null,
    'Hot and cold are opposites! Ice is cold, fire is hot!'),
  mcq('Opposite of "up"?','down','high','top','sky',null,
    'Up and down are opposites — you go up the stairs and down the stairs!'),
  mcq('Opposite of "in"?','out','inside','enter','through',null,
    '"In" and "out" are opposites — you go in the door, then out the door!'),
  // ── Rhyming ──
  mcq('Which word rhymes with "rain"?','train','cloud','snow','hail',null,
    '"rain" and "train" both end in "-ain"! They share the same sound!'),
  mcq('Which word rhymes with "night"?','light','moon','dark','cloud',null,
    '"night" and "light" both end in "-ight"! They rhyme!'),
  // ── Extra spelling ──
  mcq('Which is the correct spelling?','people','peeple','pepole','peaple',null,
    '"people" — P-E-O-P-L-E. One of the trickiest Year 1 words!'),
  mcq('Which is correct?','here','heer','hear','heir',null,
    '"here" means a place — H-E-R-E. Not the same as "hear" (with your ears)!'),
  mcq('Correct spelling:','when','wen','whin','whan',null,
    '"when" — W-H-E-N. It starts with a silent H after the W!'),
  mcq('Correct spelling:','does','duz','doez','doas',null,
    '"does" — D-O-E-S. Looks like "goes" — same pattern!'),
  typed('Spell the opposite of "night":','day',['day'],null,
    'Day is spelled D-A-Y! Three letters: D, A, Y!'),
  typed('Spell the word for a body of water you swim in: 🏊','sea',['sea'],null,
    '"sea" is spelled S-E-A! The "ea" makes a long "ee" sound!'),
  mcq('Which word names a person who treats sick animals?','vet','doctor','nurse','chef','🐾',
    'A vet is a doctor for animals — short for "veterinarian"!'),
  mcq('Which word is a verb (action word)?','jump','table','red','quickly',null,
    'A verb is a doing or action word — "jump", "eat", "sleep", "run" are all verbs!'),
];}

function qYear2() { return [
  // ── Year 2 exception words spelling ──
  mcq('Correct spelling:','because','becuase','becose','becaus',null,
    '"because" — B-E-C-A-U-S-E. Tip: Big Elephants Can Always Understand Small Elephants!'),
  mcq('Correct spelling:','February','Febuary','Feburary','Februery',null,
    '"February" — F-E-B-R-U-A-R-Y. Don\'t forget the hidden R: Feb-R-uary!'),
  mcq('Correct spelling:','Wednesday','Wensday','Wenesday','Wednessday',null,
    '"Wednesday" — W-E-D-N-E-S-D-A-Y. Hidden "D": Wed-nes-day!'),
  mcq('Correct spelling:','beautiful','beatiful','butiful','beutiful',null,
    '"beautiful" — B-E-A-U-T-I-F-U-L. Think "beau" at the start!'),
  mcq('Correct spelling:','every','evry','evrey','eveery',null,
    '"every" — E-V-E-R-Y. Five letters — don\'t forget the E in the middle!'),
  mcq('Correct spelling:','island','iland','ilsand','isalnd',null,
    '"island" — I-S-L-A-N-D. The S is silent — "i-land"!'),
  mcq('Correct spelling:','clothes','cloths','cloeths','cloaths',null,
    '"clothes" — C-L-O-T-H-E-S. Don\'t forget the silent E near the end!'),
  mcq('Correct spelling:','sugar','shoogar','suger','shuggar',null,
    '"sugar" — S-U-G-A-R. The "su" makes a "sh" sound — tricky!'),
  mcq('Correct spelling:','money','muney','mony','monney',null,
    '"money" — M-O-N-E-Y. The O makes a short "u" sound — unusual!'),
  mcq('Correct spelling:','many','meny','manny','maney',null,
    '"many" — M-A-N-Y. Short and simple — four letters!'),
  typed('Spell the word for what the weather is like today:','weather',['weather'],null,
    '"weather" — W-E-A-T-H-E-R. The "ea" makes a short "e" sound!'),
  typed('Spell the word that means "even though":','although',['although'],null,
    '"although" — A-L-T-H-O-U-G-H. A useful connective word!'),
  // ── Plurals ──
  mcq('Which is the correct plural of "child"?','children','childs','childes','childrens',null,
    '"children" is an irregular plural — it doesn\'t follow the usual +s rule!'),
  mcq('Which sentence is correct?','I saw two deer.','I saw two deers.','I saw two deeres.','I saw two dear.',null,
    '"deer" stays the same in plural — like "sheep"! One deer, two deer!'),
  typed('Spell the plural of "mouse".','mice',['mice'],null,
    '"mice" is the irregular plural of "mouse" — one mouse, two mice!'),
  mcq('What is the plural of "box"?','boxes','boxs','boxen','boxi',null,
    'Words ending in X get "-es" in the plural — box → boxes!'),
  mcq('What is the plural of "fly"?','flies','flys','flyes','fliy',null,
    'Words ending in consonant + Y change Y to I and add "-es" — fly → flies!'),
  mcq('What is the plural of "foot"?','feet','foots','footes','footis',null,
    '"feet" is the irregular plural of "foot" — one foot, two feet!'),
  mcq('What is the plural of "tooth"?','teeth','tooths','toothes','tooths',null,
    '"teeth" is the irregular plural of "tooth" — just like foot/feet!'),
  // ── Adverbs ──
  mcq('A word that describes a verb is a/an:','adverb','adjective','noun','pronoun',null,
    'An adverb describes HOW a verb is done — "quickly", "loudly", "carefully"!'),
  mcq('"The dog ran ___." Which adverb fits?','quickly','quick','quicker','quickest',null,
    '"quickly" is an adverb — it describes HOW the dog ran!'),
  mcq('Which word is an adverb?','loudly','loud','louder','loudness',null,
    '"loudly" ends in "-ly" — that\'s a common adverb ending! It describes HOW something is done!'),
  mcq('"She smiled ___." Choose the adverb:','happily','happy','happier','happiness',null,
    '"happily" is an adverb — it describes HOW she smiled!'),
  // ── Connectives / conjunctions ──
  mcq('Which word is a connective?','because','table','run','happy',null,
    'A connective (conjunction) joins parts of a sentence — "because", "and", "but"!'),
  mcq('Which word can join two sentences?','but','big','run','red',null,
    '"but" is a conjunction — it joins two contrasting ideas: "I like cake but not biscuits"!'),
  mcq('"I was tired ___ I stayed up late." Choose:','so','big','fast','green',null,
    '"so" shows a result — "I was tired SO I stayed up late"!'),
  // ── Tenses ──
  typed('Spell the past tense of "run".','ran',['ran'],null,
    '"ran" is the past tense of "run" — it\'s irregular, not "runned"!'),
  mcq('"I __ going to the park." Choose:','am','is','are','was',null,
    '"I am" is correct! We say: I am, he/she is, they are!'),
  mcq('Which is the past tense of "eat"?','ate','eated','have eat','ated',null,
    '"ate" is the irregular past tense of "eat" — not "eated"!'),
  mcq('Which is the past tense of "go"?','went','goed','gone','go',null,
    '"went" is the irregular past tense of "go" — not "goed"!'),
  mcq('Which verb is in the PRESENT tense?','she reads','she read','she has read','she will read',null,
    '"she reads" is happening RIGHT NOW — that\'s the present tense!'),
  // ── Silent letters ──
  mcq('Which word has a silent letter?','knife','cat','dog','run',null,
    '"knife" has a silent K — K-N-I-F-E. The "kn" makes just an "n" sound!'),
  mcq('Which word has a silent letter?','write','hat','top','big',null,
    '"write" has a silent W — W-R-I-T-E. The "wr" makes just an "r" sound!'),
  mcq('Which word has a silent letter?','gnome','game','come','name','🤫',
    '"gnome" has a silent G — G-N-O-M-E. The "gn" makes just an "n" sound!'),
  // ── Punctuation ──
  mcq('Which punctuation ends a question?','?','!','.',',',null,
    'A question mark (?) ends a question! It tells the reader to raise their voice!'),
  // ── Homophones ──
  mcq('"I went ___ the park." Which word?','to','two','too','tow',null,
    '"to" shows direction or purpose — "I went TO the park". "two" is the number 2!'),
  mcq('"There are ___ cats." Which word?','two','to','too','tow',null,
    '"two" is the number 2 — T-W-O! "to" and "too" are completely different words!'),
  mcq('"I want cake ___." Which word?','too','to','two','tow',null,
    '"too" means also or as well — "I want cake TOO!" It has two Os!'),
  // ── Opposites ──
  mcq('Opposite of "ancient"?','modern','old','tired','historic',null,
    '"Ancient" means very old. The opposite is "modern" — meaning new or current!'),
  // ── Extra typed ──
  typed('Spell the word for the day after Monday:','tuesday',['tuesday','Tuesday'],null,
    '"Tuesday" — T-U-E-S-D-A-Y. Named after Tiw, the Norse god of war!'),
  mcq('What is an antonym?','A word that means the opposite','A word that sounds the same','A word that means the same','A made-up word',null,
    'An antonym is the OPPOSITE — "hot" and "cold", "happy" and "sad" are antonyms!'),
  mcq('Which word is a synonym for "happy"?','glad','sad','angry','tired',null,
    '"glad" and "happy" mean the same thing — they are synonyms!'),
  typed('Spell the word that means the opposite of "cold":','hot',['hot'],null,
    '"hot" is the antonym (opposite) of "cold" — just three letters: H-O-T!'),
];}

function qYear3() { return [
  // ── Synonyms ──
  mcq('What is a synonym for "big"?','large','small','cold','fast',null,
    'A synonym is a word with the SAME meaning! Large, huge, enormous all mean big!'),
  mcq('What is a synonym for "happy"?','joyful','sad','angry','upset',null,
    '"joyful" means happy! A synonym shares the same meaning as another word!'),
  mcq('What is a synonym for "said"?','exclaimed','run','table','big',null,
    '"exclaimed" means said loudly or with emotion — a more powerful synonym for "said"!'),
  mcq('Choose a synonym for "small":','tiny','huge','large','enormous',null,
    '"tiny" means very small — it\'s a synonym for small!'),
  mcq('Which word is a synonym for "begin"?','start','finish','end','stop',null,
    '"start" and "begin" mean the same thing — they are synonyms!'),
  // ── Antonyms ──
  mcq('What is an antonym for "brave"?','cowardly','bold','strong','fierce',null,
    'An antonym is the OPPOSITE! "cowardly" means fearful — the opposite of brave!'),
  mcq('What is an antonym for "ancient"?','modern','old','historic','aged',null,
    '"ancient" means very old; "modern" means new. They are antonyms!'),
  mcq('Choose the antonym of "victory":','defeat','win','triumph','succeed',null,
    '"defeat" is the opposite of "victory" — winning vs losing!'),
  mcq('Antonym of "generous"?','mean','kind','giving','friendly',null,
    'A generous person gives a lot; a mean person does not. They are antonyms!'),
  // ── Spelling ──
  mcq('Correct spelling:','necessary','necesary','neccesary','necessery',null,
    '"necessary" — N-E-C-E-S-S-A-R-Y. Tip: one Collar, two Socks (1C, 2S)!'),
  mcq('Correct spelling:','separate','seperate','seperrate','separete',null,
    '"separate" — S-E-P-A-R-A-T-E. Tip: there\'s a RAT in sep-a-rat-e!'),
  mcq('Which word is spelt correctly?','believe','beleive','belive','beleave',null,
    '"believe" — B-E-L-I-E-V-E. Remember: "I before E except after C"!'),
  typed('Spell: a word meaning extremely happy (starts with D):','delighted',['delighted'],null,
    '"Delighted" means extremely happy! D-E-L-I-G-H-T-E-D!'),
  typed('Spell the word that means "to put off until later":','postpone',['postpone'],null,
    '"postpone" means to delay something — P-O-S-T-P-O-N-E!'),
  // ── Prefixes and suffixes ──
  mcq('What does the prefix "un-" mean?','not','again','before','after',null,
    'The prefix "un-" means NOT — unhappy=not happy, unkind=not kind!'),
  mcq('What does the suffix "-ful" mean?','full of','without','having','able to',null,
    'The suffix "-ful" means full of — careful=full of care, joyful=full of joy!'),
  mcq('What does the prefix "re-" mean?','again','not','before','badly',null,
    '"re-" means AGAIN — redo, rewrite, replay, return!'),
  mcq('What does the suffix "-less" mean?','without','full of','again','before',null,
    '"-less" means WITHOUT — hopeless=without hope, careless=without care!'),
  mcq('Which word contains a prefix meaning "not"?','disagree','replay','careful','joyful',null,
    '"disagree" — the prefix "dis-" means NOT — to disagree means to NOT agree!'),
  mcq('What is the root word in "unhappy"?','happy','un','unhapp','happ',null,
    '"un" is the prefix (meaning NOT), and "happy" is the ROOT word!'),
  mcq('What is the root word in "preview"?','view','pre','previe','iew',null,
    '"pre-" is the prefix (meaning BEFORE), and "view" is the ROOT word!'),
  // ── Pronouns ──
  mcq('A word that replaces a noun is a:','pronoun','adverb','adjective','verb',null,
    'A pronoun replaces a noun — instead of "Sarah", we say "she"!'),
  mcq('Which word is a pronoun?','they','table','happy','run',null,
    '"they" is a pronoun — it replaces a group of nouns. "They went to the park."'),
  mcq('"___ finished the homework." Which pronoun?','She','Quick','Table','Bright',null,
    '"She" is a pronoun that replaces a girl\'s name — "She finished the homework."'),
  // ── Conjunctions ──
  mcq('Which is NOT a conjunction?','table','and','but','because',null,
    'Conjunctions join ideas: "and", "but", "because". A "table" is a piece of furniture!'),
  mcq('Which conjunction shows contrast?','although','and','so','because',null,
    '"although" shows contrast — "Although it rained, we had fun." It means "even though"!'),
  mcq('"I was tired ___ I went to bed." Choose:','so','but','or','nor',null,
    '"so" shows a result — "I was tired SO I went to bed"!'),
  // ── Collective nouns ──
  mcq('"A ____ of lions" — collective noun:','pride','group','gang','team',null,
    'A group of lions is called a "pride" — collective nouns are special group names!'),
  mcq('"A ____ of birds" — collective noun:','flock','gang','pack','pride',null,
    'A group of birds is called a "flock" — like a flock of sparrows!'),
  mcq('"A ____ of wolves" — collective noun:','pack','flock','pride','cluster',null,
    'A group of wolves is called a "pack" — dogs also live in packs!'),
  // ── Tenses ──
  mcq('"The children ___ playing." Choose:','were','was','is','be',null,
    '"children" is plural, so we use "were" not "was"!'),
  mcq('Which tense is "She will travel"?','future','past','present','pluperfect',null,
    '"will travel" means it hasn\'t happened yet — it\'s in the FUTURE tense!'),
  mcq('Which is the PAST tense?','She ran quickly.','She runs quickly.','She is running.','She will run.',null,
    '"ran" is the past tense of "run" — it already happened!'),
  // ── Similes ──
  mcq('What is a simile?','A comparison using "like" or "as"','Saying something IS something else','A repeated sound','An exaggeration',null,
    'A simile COMPARES using "like" or "as" — "as brave as a lion" or "runs like the wind"!'),
  mcq('Which is a simile?','He ran like the wind.','He is a tiger.','The moon smiled.','She flew quickly.',null,
    '"He ran LIKE the wind" — the word "like" makes it a simile (a comparison)!'),
  mcq('"As cold as ice" is an example of:','a simile','a metaphor','alliteration','personification',null,
    '"as cold as ice" uses "as...as" to make a comparison — that\'s a simile!'),
  // ── Correct tense usage ──
  mcq('Which sentence is correct?','Yesterday, I ate my lunch.','Yesterday, I eat my lunch.','Yesterday, I eats my lunch.','Yesterday, I eating my lunch.',null,
    '"ate" is the past tense of "eat". "Yesterday" tells us it\'s in the past!'),
  typed('Spell the word for doing something by yourself — without help:','independently',['independently'],null,
    '"independently" — I-N-D-E-P-E-N-D-E-N-T-L-Y. The root word is "depend"!'),
  typed('Spell the word for something that can be seen:','visible',['visible'],null,
    '"visible" — V-I-S-I-B-L-E. From Latin "visibilis" — able to be seen!'),
  mcq('What is an abstract noun?','A noun you cannot touch or see — a feeling or idea','A noun that is very large','A type of verb','A describing word',null,
    'Abstract nouns are things you can FEEL but not touch — love, fear, freedom, happiness, courage!'),
  mcq('Which is an abstract noun?','joy','chair','dog','mountain',null,
    '"joy" is an abstract noun — you can FEEL it but you cannot touch it!'),
  mcq('What is a pronoun?','A word that replaces a noun','A very powerful noun','A type of adjective','A joining word',null,
    'Pronouns replace nouns so we don\'t repeat them — "Emma is kind. SHE is my friend."'),
  typed('Type the ROOT word of "unhappiness":','happy',['happy'],null,
    '"unhappiness" = prefix "un-" + root "happy" + suffix "-ness". Strip the prefix and suffix!'),
];}

function qYear4() { return [
  // ── Homophones ──
  mcq('What are homophones?','words that sound the same but have different meanings','words that mean the same','words that are opposites','made-up words',null,
    'Homophones sound IDENTICAL when spoken but have different spellings — like "there/their"!'),
  mcq('Which pair are homophones?','there / their','big / large','run / ran','happy / glad',null,
    '"there" (a place) and "their" (belonging to them) sound the same — they\'re homophones!'),
  mcq('"___ going to be late." Which word?','They\'re','Their','There','They',null,
    '"They\'re" is short for "they are" — "They\'re going to be late."'),
  mcq('"Put it over ___." Which word?','there','their','they\'re','thear',null,
    '"there" refers to a place — "put it over THERE." Think: "here" is in "there"!'),
  mcq('"It\'s ___ turn." Which word?','their','there','they\'re','thier',null,
    '"their" shows belonging — "it\'s THEIR turn." Think: "heir" is in "their"!'),
  mcq('Which pair are homophones?','flour / flower','cat / kitten','fast / slow','big / large','🌸',
    '"flour" (for baking) and "flower" (a plant) sound exactly the same!'),
  mcq('"I can ___ the music." Which word?','hear','here','heer','heir',null,
    '"hear" is what you do with your ears — H-E-A-R. "ear" is hiding inside "hear"!'),
  mcq('"The cake is ___ in the oven." Which word?','there','their','they\'re','thair',null,
    '"there" is a place word — "the cake is over THERE"!'),
  // ── Possessive apostrophes ──
  mcq('What is the correct possessive?',"the dog's lead","the dogs lead","the dogs' lead","the dog lead",null,
    '"the dog\'s lead" — the apostrophe + s shows the lead BELONGS to the dog!'),
  mcq('Which is correct?',"the girl's book","the girls book","the girls' book","the girls\\'s book",null,
    '"the girl\'s book" — one girl, so apostrophe + s. The book belongs to one girl!'),
  mcq('"The ___ toys are here." (many dogs)','dogs\'','dog\'s','dogs','dogss',null,
    'For plural nouns ending in S, put the apostrophe AFTER the S — "the dogs\' toys"!'),
  mcq('Which shows something belonging to James?',"James's bag","James bag","James' bag","Jamess bag",null,
    '"James\'s bag" — for names ending in S, we still add \'s to show possession!'),
  // ── Compound sentences ──
  mcq('Which is a compound sentence?','I like cats, and my sister likes dogs.','I like cats.','Because I like cats.','Although.',null,
    'A compound sentence has TWO main clauses joined by a conjunction like "and" or "but"!'),
  mcq('What joins two main clauses in a compound sentence?','a coordinating conjunction','a comma','a colon','a semicolon',null,
    'Coordinating conjunctions (FANBOYS: For, And, Nor, But, Or, Yet, So) join two main clauses!'),
  mcq('Which word is a coordinating conjunction?','but','although','because','since',null,
    '"but" is a coordinating conjunction — it joins two equal main clauses!'),
  // ── Modal verbs ──
  mcq('Identify the modal verb: "You should eat vegetables."','should','eat','vegetables','you',null,
    'Modal verbs show possibility or obligation — "should", "must", "can", "will", "might"!'),
  mcq('Which is a modal verb?','might','eat','happy','green',null,
    '"might" is a modal verb — it shows possibility. "She might come to the party."'),
  mcq('Which sentence uses a modal verb?','You must wear a coat.','She wore a coat.','The coat is warm.','Coats are useful.',null,
    '"must" is a modal verb showing obligation — you MUST do it!'),
  mcq('"She ___ swim very well." Which modal verb fits?','can','eats','runs','jump',null,
    '"can" is a modal verb showing ability — "she CAN swim" means she has the skill!'),
  // ── Prefix meanings ──
  mcq('What does the prefix "mis-" mean?','wrongly','again','not','before',null,
    'The prefix "mis-" means done wrongly — misunderstand, misspell, misbehave!'),
  mcq('Which word has the prefix "pre-"?','preview','review','overview','subview',null,
    '"pre-" means BEFORE — "preview" means to view something BEFORE its official release!'),
  mcq('What does "inter-" mean?','between','against','under','over',null,
    '"inter-" means BETWEEN — international=between nations, interact=act between each other!'),
  mcq('What does "super-" mean?','above/beyond','under','against','between',null,
    '"super-" means above or beyond — superhero, supermarket, supernatural!'),
  mcq('What does "sub-" mean?','under/below','over','between','around',null,
    '"sub-" means under or below — submarine=under the sea, subheading=under a heading!'),
  // ── Spelling ──
  mcq('Correct spelling:','conscience','consience','consciense','concience',null,
    '"conscience" — C-O-N-S-C-I-E-N-C-E. Your conscience is your inner sense of right and wrong!'),
  mcq('Correct spelling:','parliament','parliment','parlamente','parliamant',null,
    '"parliament" — P-A-R-L-I-A-M-E-N-T. Tricky middle: "lia" not "lie"!'),
  mcq('Correct spelling:','privilege','priviledge','privelege','privelidge',null,
    '"privilege" — P-R-I-V-I-L-E-G-E. No D — "privi-LEGE" not "privi-LEDGE"!'),
  mcq('Correct spelling:','environment','enviroment','envieronment','enviornment',null,
    '"environment" — E-N-V-I-R-O-N-M-E-N-T. Don\'t forget the hidden N before M!'),
  typed('What word means "a word that means the same as another"?','synonym',['synonym'],null,
    'A "synonym" is a word meaning the same as another — "happy" and "glad" are synonyms!'),
  typed('Spell the word for the fear of spiders:','arachnophobia',['arachnophobia'],null,
    '"arachnophobia" — A-R-A-C-H-N-O-P-H-O-B-I-A. "arachno" = spider, "phobia" = fear!'),
  // ── Word classes ──
  mcq('Which sentence uses an adverb?','She sang beautifully.','She is beautiful.','The beautiful song.','Beauty is great.',null,
    '"beautifully" describes HOW she sang — that\'s an adverb!'),
  mcq('Which word is an abstract noun?','happiness','table','run','quickly',null,
    'An abstract noun is something you FEEL but can\'t touch — like happiness, fear, love!'),
  // ── Formal vs informal ──
  mcq('Which is FORMAL language?','I would be grateful for your assistance.','Can ya help me?','Cheers mate!','Wanna come?',null,
    'Formal language is polite and professional — used in letters, essays, and school work!'),
  mcq('Which is INFORMAL language?','See ya later!','I will be in attendance.','Dear Sir or Madam','I am writing to enquire',null,
    'Informal language is casual and friendly — used with friends and family!'),
  // ── Punctuation ──
  mcq('What punctuation is used in a list?','comma','colon','semicolon','full stop',null,
    'Commas separate items in a list — they give the reader a brief pause between items!'),
  typed('Spell the word for a verb that shows ability, permission or possibility:','modal',['modal'],null,
    'A "modal" verb (like can, could, may, might) shows ability, permission or possibility!'),
  // ── Agreement ──
  mcq('"Running every day __ her fit." Choose:','kept','keep','keeps','keeping',null,
    '"kept" is past tense and agrees with the habitual action — "Running kept her fit"!'),
  mcq('"Despite the rain, ___ went outside." Choose:','they','them','their','there',null,
    '"they" is a subject pronoun — it does the action! "them" is an object pronoun!'),
  mcq('What is the effect of a fronted adverbial?','It moves an adverbial phrase to the START of a sentence for emphasis','It ends the sentence','It replaces a noun','It joins two sentences',null,
    'A fronted adverbial comes FIRST and has a comma after it — "At sunrise, the birds sang"!'),
  mcq('Which uses a fronted adverbial correctly?','In the morning, she jogged for an hour.','She jogged for an hour in the morning.','She, in the morning, jogged.','She jogged, in the morning.',null,
    '"In the morning," is placed at the FRONT with a comma — that\'s a fronted adverbial!'),
  mcq('What is an adverbial phrase?','A group of words that tells when, where or how','A type of noun phrase','A kind of adjective','A conjunction',null,
    'Adverbial phrases tell us WHEN ("in the morning"), WHERE ("at the park"), or HOW ("with great care")!'),
  typed('What word class is "because"?','conjunction',['conjunction'],null,
    '"because" is a conjunction (subordinating conjunction) — it joins a main clause to a subordinate clause!'),
  mcq('Which sentence uses parenthesis correctly?','The Eiffel Tower (built in 1889) is in Paris.','The Eiffel Tower, built (in 1889) is in Paris.','The Eiffel Tower built in 1889 (is in Paris).','(The Eiffel Tower built in 1889 is) in Paris.',null,
    'Parenthesis adds extra info using brackets — remove it and "The Eiffel Tower is in Paris" still works!'),
];}

function qYear5() { return [
  // ── Relative clauses ──
  mcq('What is a relative clause?','A clause that gives more information about a noun','A type of noun','A verb phrase','A kind of adjective',null,
    'A relative clause gives MORE info about a noun — "the boy WHO won" — "who won" is the relative clause!'),
  mcq('Which relative pronoun introduces a clause about a person?','who','which','that','where',null,
    '"who" introduces a relative clause about a PERSON — "the teacher who helped me"!'),
  mcq('Which relative pronoun introduces a clause about a thing?','which','who','whom','whose',null,
    '"which" introduces a relative clause about a THING — "the book which I lost"!'),
  mcq('Identify the relative clause: "The dog that barked was mine."','that barked','The dog','was mine','The dog that',null,
    '"that barked" gives extra information about the dog — it\'s the relative clause!'),
  // ── Semicolons ──
  mcq('Which sentence uses a semicolon correctly?','I love summer; the days are long.','I love; summer the days are long.','I; love summer the days are long.','I love summer the; days are long.',null,
    'A semicolon (;) joins two RELATED main clauses — "I love summer; the days are long."!'),
  mcq('What does a semicolon do?','Joins two closely related main clauses','Separates items in a list','Introduces a quotation','Shows possession',null,
    'A semicolon joins two closely related main clauses without using a conjunction!'),
  mcq('Which is the best use of a semicolon?','It was raining; we stayed inside.','It was; raining we stayed inside.','It was raining we; stayed inside.','It was raining we stayed; inside.',null,
    '"It was raining; we stayed inside" — the two ideas are closely connected!'),
  // ── Metaphors ──
  mcq('What is a metaphor?','Saying something IS something else','Comparing using like or as','A repeated beginning sound','A made-up word',null,
    'A metaphor says something IS something else — "He is a lion" (not "like a lion")!'),
  mcq('Which is a metaphor?','Life is a journey.','Life is like a journey.','He runs like a cheetah.','She is as cold as ice.',null,
    '"Life IS a journey" — no "like" or "as", it says life IS a journey. That\'s a metaphor!'),
  mcq('What is the difference between a metaphor and a simile?','A simile uses "like" or "as"; a metaphor does not','They are the same thing','A metaphor uses "like"; a simile does not','A metaphor is always about nature',null,
    'A simile uses "like" or "as" to compare. A metaphor says one thing IS another!'),
  // ── Similes ──
  mcq('What is a simile?','A comparison using "like" or "as"','A type of noun','A repeated vowel sound','A shortened word',null,
    'A simile COMPARES using "like" or "as" — "as brave as a lion" or "runs like the wind"!'),
  mcq('Which is a simile?','She runs like the wind.','She is the wind.','The wind howled.','She ran quickly.',null,
    '"She runs LIKE the wind" — using "like" makes it a simile!'),
  // ── Personification ──
  typed('What literary device is "The wind whispered"?','personification',['personification'],null,
    'Personification gives human qualities to non-human things — wind can\'t really whisper!'),
  mcq('"The angry storm tore the trees apart." Which device?','personification','simile','metaphor','alliteration',null,
    'Storms can\'t feel anger — giving human emotions to the storm is PERSONIFICATION!'),
  mcq('Which sentence uses personification?','The sun danced across the sky.','The sun is very hot.','It was a sunny day.','We saw the bright sun.',null,
    '"danced" is a human action — giving it to the sun is personification!'),
  // ── Alliteration ──
  mcq('What is alliteration?','Repetition of the same consonant sound at the start of words','Rhyming words','Exaggeration','A figure of speech',null,
    'Alliteration repeats the SAME consonant sound at the start — "she sells sea shells"!'),
  mcq('Which is an example of alliteration?','Peter Piper picked peppers','The moon is round','She runs fast','He said hello',null,
    '"Peter Piper Picked Peppers" — P, P, P, P — all start with the same sound!'),
  mcq('Which phrase uses alliteration?','big brave bears','slow small snail','tired old tortoise','fast red fox',null,
    '"big brave bears" — B, B, B — three words starting with the same sound!'),
  // ── Subjunctive mood ──
  mcq('What is the subjunctive mood?','Used for hypothetical or wished-for situations','Past tense','A type of question','A describing word',null,
    'The subjunctive is used for wishes and hypotheticals — "I wish I WERE taller"!'),
  mcq('"If I ____ you, I would help." Choose:','were','was','am','be',null,
    'The subjunctive uses "were" for hypothetical situations — even "if I were you" (not "was")!'),
  mcq('Which sentence uses the subjunctive?','I wish I were taller.','I was taller once.','She is very tall.','They grew tall.',null,
    '"I wish I WERE" — not "was" — this is the subjunctive, used for wishes!'),
  // ── Passive and active voice ──
  mcq('Identify the passive voice:','The cake was eaten by the child.','The child ate the cake.','She baked a cake.','They love cakes.',null,
    'In passive voice, the subject RECEIVES the action — "The cake WAS EATEN by the child"!'),
  mcq('Which is in the ACTIVE voice?','The dog chased the cat.','The cat was chased by the dog.','The cat was being chased.','The dog was chasing.',null,
    'In active voice, the subject DOES the action — "The dog CHASED the cat"!'),
  mcq('How do you change active to passive?','Move the object to the subject and add "was/were"','Change the verb to past tense','Add a pronoun','Use a conjunction',null,
    'In passive: "The ball was kicked by Tom" — the ball (object) becomes the subject!'),
  // ── Adverbs ──
  mcq('What word class is "however"?','adverb','adjective','noun','verb',null,
    '"however" is a conjunctive adverb — it connects ideas and shows contrast!'),
  mcq('Which adverb tells you WHERE something happened?','nearby','yesterday','quickly','although',null,
    '"nearby" is an adverb of PLACE — it tells you WHERE something happened!'),
  mcq('Which adverb tells you WHEN something happened?','yesterday','loudly','happily','nearby',null,
    '"yesterday" is an adverb of TIME — it tells you WHEN something happened!'),
  mcq('Which adverb tells you HOW something was done?','gently','soon','here','often',null,
    '"gently" is an adverb of MANNER — it tells you HOW something was done!'),
  // ── Spelling ──
  mcq('Correct spelling:','accommodate','accomodate','acommodate','acomodate',null,
    '"accommodate" — A-C-C-O-M-M-O-D-A-T-E. It accommodates two Cs AND two Ms!'),
  mcq('Correct spelling:','occurrence','occurence','occurrance','ocurrence',null,
    '"occurrence" — O-C-C-U-R-R-E-N-C-E. Two Cs and two Rs — both doubled!'),
  mcq('Correct spelling:','definitely','definately','definitley','definitelyy',null,
    '"definitely" — D-E-F-I-N-I-T-E-L-Y. Spot the word "finite" hiding inside!'),
  mcq('Correct spelling:','exaggerate','exagerate','exxagerate','exaggerrate',null,
    '"exaggerate" — E-X-A-G-G-E-R-A-T-E. Double G in the middle — exaGGerate!'),
  typed('Spell the word for judging something without full knowledge:','prejudice',['prejudice'],null,
    '"prejudice" — P-R-E-J-U-D-I-C-E. "pre" means before, "judice" relates to judging!'),
  typed('Spell the word for information meant to influence people:','propaganda',['propaganda'],null,
    '"propaganda" — P-R-O-P-A-G-A-N-D-A. It\'s information used to shape opinions!'),
  // ── Extra Year 5 questions ──
  mcq('What is an ellipsis (...) used for?','To create suspense, a pause, or show something is missing','To end a sentence','To show possession','To introduce a list',null,
    'An ellipsis (...) creates a sense of pause or mystery — "Then she opened the door..."'),
  mcq('Which sentence uses an ellipsis correctly?','He looked around... nothing was there.','He...looked around nothing was there.','He looked...around nothing.','He looked around nothing...was there.',null,
    'The ellipsis comes AFTER a complete thought to build suspense — "He looked around..."!'),
  mcq('What is a compound-complex sentence?','A sentence with two main clauses AND at least one subordinate clause','A sentence with only one main clause','A very long sentence','A sentence with no verbs',null,
    'Compound-complex sentences are very sophisticated — they have TWO main clauses PLUS a subordinate clause!'),
  mcq('What is an oxymoron?','Two contradictory words placed together','A type of rhyme','An exaggeration','A word from another language',null,
    'An oxymoron puts two opposite ideas together — "deafening silence", "bittersweet", "pretty ugly"!'),
  mcq('Which is an example of an oxymoron?','bittersweet','very happy','quite large','slightly warm',null,
    '"bittersweet" — bitter and sweet are opposites! Oxymorons combine contradictory ideas!'),
  mcq('What is a discourse marker?','A word or phrase that organises and connects ideas in a text','A type of verb','A punctuation mark','A literary device',null,
    'Discourse markers guide the reader — "firstly", "however", "in conclusion", "furthermore"!'),
  mcq('Which is a discourse marker?','furthermore','table','running','happily',null,
    '"furthermore" is a discourse marker — it adds to or extends the previous point!'),
  mcq('What is the purpose of imagery in writing?','To create pictures in the reader\'s mind using descriptive language','To list facts','To correct grammar','To count syllables',null,
    'Imagery uses metaphors, similes and personification to paint vivid pictures in your head!'),
  typed('What literary device repeats consonant sounds at the start of words — like "Peter Piper picked"?','alliteration',['alliteration'],null,
    '"P, P, P" — repeating the same consonant sound at the start of words is ALLITERATION!'),
];}

function qYear6() { return [
  // ── Parenthesis ──
  mcq('What is a parenthesis?','Extra information added to a sentence using brackets, dashes or commas','A type of verb','A form of punctuation','A kind of noun',null,
    'A parenthesis adds extra info using brackets ( ), dashes — —, or commas. Remove it and the sentence still makes sense!'),
  mcq('Which uses parenthesis correctly?','My friend — who lives nearby — is kind.','My friend, who — lives nearby is kind.','— My friend who lives nearby is — kind.','My friend who lives, nearby — is kind.',null,
    'The dashes surround the extra information — "who lives nearby" — which can be removed!'),
  mcq('Which uses brackets correctly?','The Aztecs (who lived in Mexico) built pyramids.','The Aztecs who (lived in Mexico) built pyramids.','The Aztecs who lived (in Mexico built) pyramids.','(The Aztecs) who lived in Mexico built pyramids.',null,
    'Brackets enclose extra information — remove "who lived in Mexico" and the sentence still works!'),
  mcq('What happens if you remove a parenthesis?','The sentence still makes complete sense.','The sentence becomes a question.','The sentence loses its main verb.','The sentence becomes incorrect.',null,
    'A parenthesis is EXTRA information — the sentence works perfectly without it!'),
  // ── Rhetorical questions ──
  mcq('Which is an example of a rhetorical question?','Isn\'t that obvious?','What is 2+2?','Where are you?','Who came last?',null,
    'A rhetorical question doesn\'t need an answer — it\'s used for effect to make you think!'),
  mcq('Why do writers use rhetorical questions?','To involve the reader and make them think','To ask for information','To show they don\'t know something','To add punctuation variety',null,
    'Rhetorical questions engage the reader — "Can we afford to ignore this?" makes you think!'),
  mcq('Which is NOT a rhetorical question?','What time does the train leave?','Isn\'t life wonderful?','Haven\'t we waited long enough?','Who could forget that day?',null,
    '"What time does the train leave?" is a genuine question needing a real answer!'),
  // ── Euphemisms ──
  mcq('What is a euphemism?','A mild word used instead of a harsh one','An exaggeration','A comparison','A repeated sound',null,
    'A euphemism replaces a harsh word with a gentler one — "passed away" instead of "died"!'),
  mcq('Which is a euphemism?','passed away','ran quickly','shone brightly','spoke loudly',null,
    '"passed away" is a gentle way of saying "died" — that\'s a euphemism!'),
  mcq('"Let go" (meaning "fired from a job") is a:','euphemism','metaphor','simile','alliteration',null,
    '"Let go" softens the harsh reality of being fired — it\'s a euphemism!'),
  // ── Hyperbole ──
  typed('What literary device involves obvious exaggeration?','hyperbole',['hyperbole'],null,
    'Hyperbole is OBVIOUS exaggeration for effect — "I\'ve told you a million times!" (not literally!)'),
  mcq('Which is an example of hyperbole?','I\'ve told you a million times!','She ran quickly.','The sky is blue.','He is as tall as a tree.',null,
    '"A million times!" — obviously an exaggeration for dramatic effect — that\'s hyperbole!'),
  mcq('What is the purpose of hyperbole?','To emphasise or exaggerate for effect','To make a direct comparison','To give human qualities to objects','To describe using the senses',null,
    'Hyperbole exaggerates wildly to emphasise a point — "I\'m so hungry I could eat a horse!"'),
  mcq('Which is hyperbole?','My bag weighs a tonne!','My bag is heavy.','My bag is very heavy.','My bag feels heavier today.',null,
    '"weighs a tonne" is obviously exaggerated — that\'s hyperbole!'),
  // ── Onomatopoeia ──
  mcq('What is onomatopoeia?','A word that sounds like what it describes','A figure of speech using comparison','A repeated sound pattern','A type of noun',null,
    'Onomatopoeia = words that SOUND like what they describe — "buzz", "sizzle", "crash", "bang"!'),
  mcq('Which word is an example of onomatopoeia?','sizzle','happy','quickly','large',null,
    '"sizzle" sounds like the noise of frying food — that\'s onomatopoeia!'),
  mcq('Which is onomatopoeia?','crash','beautiful','slowly','enormous',null,
    '"crash" sounds like the noise it describes — a loud crashing sound!'),
  typed('Name a word that sounds like a snake hissing:','hiss',['hiss'],null,
    '"hiss" is onomatopoeia — the word SOUNDS like the noise a snake makes!'),
  // ── Literary devices identification ──
  mcq('"The sizzling sausages" — which device?','alliteration','metaphor','onomatopoeia','personification',null,
    '"Sizzling" and "sausages" both start with the "s" sound — that\'s alliteration!'),
  mcq('"The thunder roared angrily" — which device?','personification','simile','alliteration','hyperbole',null,
    'Thunder can\'t actually feel anger — giving it human emotions is PERSONIFICATION!'),
  mcq('"The classroom was a zoo." — which device?','metaphor','simile','onomatopoeia','hyperbole',null,
    '"The classroom WAS a zoo" — no "like" or "as", it says the classroom IS a zoo. Metaphor!'),
  mcq('"She was as quiet as a mouse." — which device?','simile','metaphor','personification','hyperbole',null,
    '"as quiet AS a mouse" — using "as" to compare. That\'s a simile!'),
  // ── Subordinate clauses ──
  mcq('What is a subordinate clause?','A clause that cannot stand alone and depends on the main clause','A main clause','A type of sentence','An independent clause',null,
    'A subordinate clause CANNOT stand alone — "Although it was raining" needs a main clause!'),
  mcq('Identify the subordinate clause: "Although it was cold, we played outside."','Although it was cold','we played outside','we played','it was cold',null,
    '"Although it was cold" can\'t stand alone as a sentence — it\'s the subordinate clause!'),
  mcq('Which word introduces a subordinate clause?','although','and','but','so',null,
    '"although" is a subordinating conjunction — it introduces a subordinate clause!'),
  // ── Colons ──
  mcq('Identify the correct use of a colon:','There is one rule: never lie.','There is: one rule never lie.','There is one: rule never lie.','There: is one rule never lie.',null,
    'A colon (:) introduces an explanation — "There is one rule: never lie" explains the rule!'),
  mcq('What can a colon introduce?','A list or an explanation','A question','A noun phrase','A subordinate clause',null,
    'A colon introduces a list or explanation — "I need three things: bread, milk, and eggs."'),
  mcq('Which is the correct use of a colon?','We visited three cities: Paris, London, and Rome.','We: visited three cities Paris, London, and Rome.','We visited: three cities Paris, London, and Rome.','We visited three cities Paris: London, and Rome.',null,
    'The colon comes AFTER the main clause and BEFORE the list — "three cities: Paris, London, Rome"!'),
  // ── Verbose and concise ──
  mcq('What does "verbose" mean?','Using more words than necessary','Brief and to the point','Full of errors','Very creative',null,
    '"Verbose" comes from Latin "verbum" (word) — verbose speech uses far more words than needed!'),
  mcq('Which sentence is most concise?','It rained.','The weather conditions resulted in the precipitation of water.','Due to meteorological events, rain occurred.','There was rain happening outside.',null,
    '"It rained" — short, clear, and says exactly what happened. Concise means using fewer words!'),
  // ── Subjunctive and other grammar ──
  mcq('Identify the subjunctive:','I suggest that he be present.','He is present.','He was present.','He will be present.',null,
    '"I suggest that he BE present" — the subjunctive "be" (not "is") follows verbs of suggestion!'),
  mcq('"Despite his fears, he performed brilliantly." What does "despite" show?','contrast/concession','addition','cause','time',null,
    '"Despite" introduces a contrast — it means "even though" or "regardless of"!'),
  // ── Spelling ──
  mcq('Correct spelling:','bureaucracy','beaurocracy','bureacracy','buerocracy',null,
    '"bureaucracy" — B-U-R-E-A-U-C-R-A-C-Y. From French "bureau" (office) + Greek "-cracy" (rule)!'),
  mcq('Correct spelling:','Mediterranean','Mediteranean','Mediterranian','Mediterrenean',null,
    '"Mediterranean" — M-E-D-I-T-E-R-R-A-N-E-A-N. Two Rs! From Latin: "middle of the earth"!'),
  mcq('Correct spelling:','conscientious','consientious','consceintious','consciencious',null,
    '"conscientious" — C-O-N-S-C-I-E-N-T-I-O-U-S. A very tricky word meaning careful and thorough!'),
  mcq('Correct spelling:','exquisite','exqisite','exquisit','exwizite',null,
    '"exquisite" — E-X-Q-U-I-S-I-T-E. It means extremely beautiful or delicately made!'),
  typed('What is the term for giving human qualities to non-human things?','personification',['personification'],null,
    'Personification gives human feelings or actions to non-human things — "the moon smiled"!'),
  typed('What is the term for the repetition of a beginning consonant sound?','alliteration',['alliteration'],null,
    'Alliteration repeats the same consonant sound at the start of words — "silly slippery snakes"!'),
  // ── Extra Year 6 questions ──
  mcq('What is anaphora?','Repetition of a word or phrase at the start of successive clauses for emphasis','A type of full stop','A linking word','A subordinate clause',null,
    'Anaphora repeats words at the start for emotional impact — "We shall fight... we shall fight... we shall fight!"'),
  mcq('"I have a dream... I have a dream..." — what device is this?','anaphora','simile','metaphor','hyperbole',null,
    'Martin Luther King repeated "I have a dream" to build powerful emphasis — that\'s anaphora!'),
  mcq('What is the difference between "who" and "whom"?','"Who" is a subject pronoun; "whom" is an object pronoun','They mean exactly the same thing','"Whom" is used for things, "who" for people','"Who" is formal; "whom" is casual',null,
    'Tip: if you can replace with "he", use "who"; if you can replace with "him", use "whom"!'),
  mcq('Which sentence is grammatically correct?','To whom was the letter addressed?','To who was the letter addressed?','The letter was addressed to who?','Whom did write the letter?',null,
    '"To whom" is correct — "whom" is used as the object of a preposition like "to"!'),
  mcq('What does "irony" mean in literature?','When reality is the opposite of what is expected, or saying the opposite of what you mean','A type of sad ending','A repeated pattern','A comparison using "like"',null,
    'Irony appears when the opposite of what is expected happens — or when someone says the opposite of what they mean!'),
];}
