// ── Grammar Quiz Question Bank ────────────────────────────────
// Each question: { question, answers[], correct (index), explanation }
// explanation shows for both correct AND incorrect answers in quiz-engine

function getGrammarQuestions(level) {
  switch (level) {
    case 'reception': return grmReception();
    case 'year1':     return grmYear1();
    case 'year2':     return grmYear2();
    case 'year3':     return grmYear3();
    case 'year4':     return grmYear4();
    case 'year5':     return grmYear5();
    case 'year6':     return grmYear6();
    default:          return grmYear1();
  }
}

function grmQ(question, answers, correct, explanation, emoji) {
  return { question, answers, correct, explanation, emoji: emoji || null };
}

// ── Reception (Age 4–5) ─────────────────────────────────────
function grmReception() {
  return [
    // ── Original 15 questions ──
    grmQ('Which sentence is written correctly?',
      ['the dog ran fast.', 'The dog ran fast.', 'the Dog ran fast.', 'the dog Ran fast.'],
      1, 'Every sentence starts with a big capital letter! 🔠', '🐶'),
    grmQ('What do we put at the END of a sentence?',
      ['A comma (,)', 'A full stop (.)', 'A question mark (?)', 'Nothing'],
      1, 'A full stop (.) tells us the sentence has finished!'),
    grmQ('Which word should have a capital letter?',
      ['run', 'big', 'emma', 'fast'],
      2, 'People\'s names always start with a capital letter! Emma is a name. 👧'),
    grmQ('Which is a complete sentence?',
      ['The big', 'Running fast', 'The cat sat on the mat.', 'A red'],
      2, 'A complete sentence makes sense on its own and has a full stop! ✅'),
    grmQ('Which sentence is a question?',
      ['The bird can fly.', 'I like cake.', 'Can birds fly?', 'Birds have wings.'],
      2, 'Questions ask something and end with a question mark (?). 🤔'),
    grmQ('Which word is a NAME?',
      ['jump', 'blue', 'happy', 'Liam'],
      3, 'Names of people and places start with a capital letter! 👦'),
    grmQ('Where does a capital letter go?',
      ['In the middle of a sentence', 'At the start of a sentence', 'At the end of a sentence', 'On every word'],
      1, 'Capital letters go at the very START of every sentence! ✍️'),
    grmQ('Which sentence ends correctly?',
      ['I like ice cream?', 'I like ice cream!', 'I like ice cream,', 'I like ice cream'],
      1, '"I like ice cream!" uses an exclamation mark to show excitement! 🍦'),
    grmQ('How many sentences are in this: "The cat sat. The dog ran."?',
      ['One', 'Two', 'Three', 'Four'],
      1, 'Each full stop ends one sentence. Two full stops = two sentences! ✌️'),
    grmQ('Which word is an ANIMAL?',
      ['run', 'cat', 'blue', 'happy'],
      1, 'A cat is a naming word (noun). Nouns are names of things, people, or animals! 🐱'),
    grmQ('Which is the correct way to start? "___ am happy."',
      ['i', 'I', 'ı', 'ii'],
      1, 'The word "I" is always written as a big capital letter — all on its own! 👆'),
    grmQ('Which sentence has a QUESTION MARK?',
      ['I love you.', 'Stop!', 'What is your name?', 'We went to school.'],
      2, 'Question marks (?) go at the end of questions — things we want to know! 🤔'),
    grmQ('Which word is an ACTION word (verb)?',
      ['cat', 'red', 'jump', 'happy'],
      2, '"Jump" is an action word! We use verbs to describe what someone is doing. 🏃'),
    grmQ('Which sentence tells us something EXCITING?',
      ['The sun is out.', 'We went home.', 'Wow, I won!', 'The bag is big.'],
      2, 'Exclamation marks (!) show excitement or surprise! 🎉'),
    grmQ('Which of these is a WORD?',
      ['xqzp', 'cat', '1234', '???'],
      1, 'Words are groups of letters that have meaning. "Cat" is a real word! 🐱'),

    // ── New questions ──
    grmQ('Which word names a THING?',
      ['run', 'blue', 'ball', 'slowly'],
      2, 'A ball is a thing you can touch and hold — it is a naming word (noun)! 🏀'),
    grmQ('Which sentence has NO mistakes?',
      ['the sun is hot.', 'The sun is hot.', 'The Sun is hot', 'the Sun is Hot.'],
      1, 'The sentence must start with a capital letter AND end with a full stop. "The sun is hot." is correct! ☀️'),
    grmQ('Which is the name of a PLACE?',
      ['London', 'run', 'big', 'flower'],
      0, 'London is the name of a city! Names of places start with a capital letter. 🏙️'),
    grmQ('What do we call words like "cat", "ball", and "house"?',
      ['Action words', 'Naming words', 'Question words', 'Joining words'],
      1, 'Cat, ball, and house are all things — we call them naming words (nouns)! 📛'),
    grmQ('Which sentence asks a question?',
      ['I have a dog.', 'The dog is brown.', 'Do you have a dog?', 'Dogs are nice.'],
      2, '"Do you have a dog?" is a question — it wants an answer and ends with a ? 🐕'),
    grmQ('Which word is an ACTION?',
      ['flower', 'sing', 'happy', 'house'],
      1, '"Sing" is something you do — it is an action word (verb)! 🎵'),
    grmQ('How does a name ALWAYS start?',
      ['With a small letter', 'With a capital letter', 'With a number', 'With a full stop'],
      1, 'Names of people and places always start with a CAPITAL letter, like Ella or Paris! 🔤'),
    grmQ('Which sentence shows SURPRISE?',
      ['I went to school.', 'The cat is black.', 'Oh no, I dropped it!', 'We eat lunch.'],
      2, 'An exclamation mark (!) shows surprise, excitement, or strong feelings. "Oh no!" 😲'),
    grmQ('Which is a QUESTION?',
      ['She likes apples.', 'He runs fast.', 'Where is my coat?', 'We went to the park.'],
      2, '"Where is my coat?" is asking something — it needs a question mark (?). 🧥'),
    grmQ('Which word is a DESCRIBING word?',
      ['dog', 'run', 'tiny', 'park'],
      2, '"Tiny" tells us what something looks like or is like — it is a describing word (adjective)! 🔍'),
    grmQ('Which mark goes at the end of a question?',
      ['.', '!', '?', ','],
      2, 'A question mark (?) always goes at the end of a question. Is it raining? 🌧️'),
    grmQ('Which sentence is about something that ALREADY happened?',
      ['I will eat cake.', 'I eat cake.', 'I ate cake.', 'I am eating cake.'],
      2, '"I ate cake" tells us it already happened — the action is in the past! 🎂'),
    grmQ('Which word is a COLOUR?',
      ['jump', 'red', 'loud', 'table'],
      1, '"Red" tells us what colour something is — it is a describing word (adjective)! 🔴'),
    grmQ('Which sentence has the RIGHT ending?',
      ['Where are you going!', 'Where are you going?', 'Where are you going.', 'Where are you going,'],
      1, 'A question like "Where are you going?" needs a question mark (?), not a full stop! 🤔'),
    grmQ('Which is NOT a sentence?',
      ['The rabbit hopped.', 'Birds can fly.', 'Big red.', 'I like chips.'],
      2, '"Big red" does not make sense on its own — it is not a complete sentence. A sentence needs a verb! 🚫'),
    grmQ('Which sentence begins correctly?',
      ['my cat is fluffy.', 'My cat is fluffy.', 'my Cat is fluffy.', 'MY cat is fluffy.'],
      1, 'Every sentence starts with ONE capital letter at the very beginning. "My cat is fluffy." ✅'),
    grmQ('Which word tells us HOW something was done?',
      ['cat', 'slowly', 'red', 'jump'],
      1, '"Slowly" tells us HOW someone moved — it is a describing word for a verb (adverb)! 🐌'),
    grmQ('Which of these is a NAME of a person?',
      ['table', 'run', 'Olivia', 'blue'],
      2, 'Olivia is a person\'s name — names always start with a capital letter! 👧'),
    grmQ('What does a FULL STOP tell us?',
      ['A question is coming', 'The sentence has ended', 'Something exciting happened', 'A list is coming'],
      1, 'A full stop (.) means the sentence is finished. Time to start a new one! 🛑'),
    grmQ('Which mark shows EXCITEMENT?',
      ['.', '?', ',', '!'],
      3, 'An exclamation mark (!) is used for exciting, surprising, or very important sentences. Wow! 🎊'),
    grmQ('Which sentence makes SENSE?',
      ['Ran the dog.', 'The dog ran.', 'Dog the ran.', 'Ran dog the.'],
      1, '"The dog ran." is in the right order — sentences need words in the right order to make sense! ✅'),
    grmQ('Which word is a SIZE word?',
      ['run', 'sing', 'huge', 'flower'],
      2, '"Huge" tells us the size of something — it is a describing word (adjective)! 🐘'),
    grmQ('Can a sentence have more than one word?',
      ['No, only one word', 'Yes, most sentences have lots of words', 'Sentences are just full stops', 'No, just two words'],
      1, 'Yes! Most sentences have several words — a subject, a verb, and often more! "The big dog ran fast." ✅'),
    grmQ('Which sentence ends with the RIGHT punctuation for a command?',
      ['Sit down please.', 'Sit down please?', 'Sit down please!', 'sit down please.'],
      2, 'Commands or instructions often end with an exclamation mark to show they are important! 📢'),
    grmQ('Which word is a NUMBER word?',
      ['run', 'three', 'blue', 'jump'],
      1, '"Three" is a number word. Numbers can be used as adjectives to describe how many! 🔢'),
    grmQ('Which sentence uses BOTH a capital letter AND a full stop?',
      ['the cat is black', 'The cat is black', 'The cat is black.', 'the cat is black.'],
      2, '"The cat is black." starts with a capital T and ends with a full stop. ✅🐈'),
    grmQ('Which is a FEELING word?',
      ['table', 'run', 'happy', 'park'],
      2, '"Happy" tells us how someone feels — it is a describing word (adjective)! 😊'),
    grmQ('What kind of mark goes at the end of "Look out"?',
      ['A full stop', 'A comma', 'A question mark', 'An exclamation mark'],
      3, '"Look out!" is a warning — warnings and commands often use exclamation marks (!)! ⚠️'),
  ];
}

// ── Year 1 (Age 5–6) ────────────────────────────────────────
function grmYear1() {
  return [
    // ── Original 15 questions ──
    grmQ('Which sentence uses capital letters correctly?',
      ['my name is jack.', 'My name is Jack.', 'My Name Is Jack.', 'my name is Jack.'],
      1, 'Capital letters start sentences AND names of people. Jack is a name! 👦'),
    grmQ('What punctuation ends a question?',
      ['Full stop (.)', 'Comma (,)', 'Question mark (?)', 'Exclamation mark (!)'],
      2, 'Questions always end with a question mark (?). Think: "What? Where? When? Why?" 🤔'),
    grmQ('Which word is a NOUN (naming word)?',
      ['run', 'happy', 'table', 'quickly'],
      2, '"Table" is a noun — it\'s the name of a thing. Nouns name people, places, and things! 🪑'),
    grmQ('Which word is a VERB (action word)?',
      ['big', 'green', 'swim', 'sad'],
      2, '"Swim" is a verb! Verbs describe actions or what someone does. 🏊'),
    grmQ('Which joining word (conjunction) fits? "I like cats ___ dogs."',
      ['but', 'because', 'and', 'so'],
      2, '"And" joins two things together when they are both true. I like cats AND dogs! 🐱🐶'),
    grmQ('Which sentence needs an exclamation mark?',
      ['I had lunch.', 'The sky is blue.', 'Watch out for the bee', 'She went home.'],
      2, '"Watch out!" shows urgency or excitement — it needs an exclamation mark (!)! 🐝'),
    grmQ('Which word is an ADJECTIVE (describing word)?',
      ['run', 'fluffy', 'eat', 'quickly'],
      1, '"Fluffy" describes what something is like. Adjectives describe nouns! 🐑'),
    grmQ('Which sentence is correct?',
      ['london is in england.', 'London is in England.', 'london is in England.', 'London is in england.'],
      1, 'Names of places like London and England always start with capital letters! 🏙️'),
    grmQ('Choose the correct sentence:',
      ['can you help me', 'Can you help me.', 'Can you help me?', 'can You help me?'],
      2, 'A question starts with a capital letter and ends with a question mark (?). 🙋'),
    grmQ('Which word joins two ideas? "I was tired ___ I kept going."',
      ['and', 'but', 'or', 'not'],
      1, '"But" connects two opposite ideas. I was tired BUT I kept going! 💪'),
    grmQ('Which punctuation mark shows a LIST? "I need milk, eggs ___ bread."',
      ['Full stops', 'Question marks', 'Commas', 'Exclamation marks'],
      2, 'Commas (,) separate items in a list. Milk, eggs AND bread! 🛒'),
    grmQ('Which word is a PLACE (proper noun)?',
      ['park', 'france', 'France', 'city'],
      2, 'France is the name of a country — proper nouns (names of places) need capital letters! 🗺️'),
    grmQ('What is a SENTENCE?',
      ['Just any word', 'A word that ends in a full stop', 'A group of words that makes complete sense', 'Two letters joined together'],
      2, 'A sentence is a group of words that makes complete sense by itself! ✅'),
    grmQ('Which word shows TIME? "___ we got home, we had dinner."',
      ['Because', 'And', 'When', 'Or'],
      2, '"When" is a conjunction that tells us about time — it links two ideas together! ⏰'),
    grmQ('Which sentence is CORRECT punctuation?',
      ['Wow that is amazing', 'Wow, that is amazing!', 'Wow. that is amazing!', 'wow, that is amazing!'],
      1, '"Wow, that is amazing!" starts with a capital, has a comma after "Wow", and ends with ! 🎉'),

    // ── New questions ──
    grmQ('Which word is a NOUN in "The happy girl danced."?',
      ['happy', 'danced', 'girl', 'the'],
      2, '"Girl" is a naming word — it is the noun in the sentence. "Happy" describes her, "danced" is the action! 💃'),
    grmQ('Which word is a VERB in "The frog jumped high."?',
      ['frog', 'high', 'the', 'jumped'],
      3, '"Jumped" is the action word (verb) — it tells us what the frog did! 🐸'),
    grmQ('Which word is an ADJECTIVE in "A tiny red bug sat still."?',
      ['bug', 'sat', 'tiny', 'still'],
      2, '"Tiny" is a describing word (adjective) — it tells us about the size of the bug! 🐞'),
    grmQ('Which joining word fits best? "She wanted to go outside ___ it was raining."',
      ['and', 'but', 'or', 'so'],
      1, '"But" shows contrast — she wanted to go out BUT it was raining. Two opposite ideas! ☔'),
    grmQ('Which sentence is a QUESTION?',
      ['The sun is bright.', 'She has a red coat.', 'Is the sun bright?', 'We saw a rainbow.'],
      2, '"Is the sun bright?" asks something — it needs a question mark (?) at the end! ☀️'),
    grmQ('Which word joins two reasons? "I stayed in ___ I was ill."',
      ['or', 'because', 'and', 'but'],
      1, '"Because" gives a reason — I stayed in BECAUSE I was ill. It explains why! 🤒'),
    grmQ('Which sentence has a CAPITAL LETTER in the wrong place?',
      ['My Dog is big.', 'My dog is big.', 'My Dog Is Big.', 'My dog is Big.'],
      1, 'Only the first word of a sentence starts with a capital. "Dog" in the middle is NOT a proper noun here! 🐕'),
    grmQ('Which is the ODD ONE OUT (not a noun)?',
      ['apple', 'school', 'quickly', 'teacher'],
      2, '"Quickly" is an adverb (it describes how something is done), not a naming word (noun)! 🍎'),
    grmQ('Which is the ODD ONE OUT (not a verb)?',
      ['run', 'laugh', 'shout', 'brave'],
      3, '"Brave" is an adjective (a describing word), not an action word (verb)! 🦁'),
    grmQ('What mark ends this sentence: "How old are you ___"',
      ['A full stop', 'A comma', 'A question mark', 'An exclamation mark'],
      2, '"How old are you?" is asking something — it must end with a question mark (?). 🎂'),
    grmQ('Which sentence uses "and" to join two IDEAS?',
      ['And I went.', 'I like cake and biscuits.', 'And.', 'And the'],
      1, '"I like cake and biscuits" — "and" links two things you like together in one sentence! 🍰🍪'),
    grmQ('Which sentence is a COMMAND?',
      ['Do you like cake?', 'She likes cake.', 'Eat your vegetables!', 'I like vegetables.'],
      2, '"Eat your vegetables!" is a command — it tells someone what to do! 🥦'),
    grmQ('How many NOUNS are in "The boy and his dog ran to the park."?',
      ['One', 'Two', 'Three', 'Four'],
      2, 'Boy, dog, and park are all nouns — naming words for a person, an animal, and a place! 🏃🐕🌳'),
    grmQ('Which word is BOTH a noun and a verb? "I had a swim. / I swim every day."',
      ['quickly', 'swim', 'happy', 'under'],
      1, '"Swim" can be a noun (a swim) or a verb (I swim). Many words can be more than one type! 🏊'),
    grmQ('Which is NOT a proper noun?',
      ['Monday', 'England', 'flower', 'Emma'],
      2, '"Flower" is a common noun — it is a general thing, not a name. Proper nouns are specific names! 🌸'),
    grmQ('Which sentence has the CORRECT use of "or"?',
      ['Do you want milk or juice?', 'Or I like milk.', 'I like or juice.', 'Or milk or.'],
      0, '"Or" offers a choice between two things: "milk or juice?" ✅ 🥛'),
    grmQ('Which word is an ADJECTIVE?',
      ['slowly', 'gigantic', 'and', 'run'],
      1, '"Gigantic" describes how big something is — it is a describing word (adjective)! 🐋'),
    grmQ('What type of word is "Monday"?',
      ['A verb', 'A common noun', 'A proper noun', 'An adjective'],
      2, '"Monday" is a proper noun — the name of a specific day. Proper nouns start with capital letters! 📅'),
    grmQ('Which sentence uses "because" correctly?',
      ['I ate because.', 'Because I ate.', 'I ate because I was hungry.', 'Because hungry I was.'],
      2, '"Because" must connect two ideas: "I ate" + reason "I was hungry". Both parts need to make sense! 🍴'),
    grmQ('Which sentence ends with a FULL STOP correctly?',
      ['The train left at noon?', 'The train left at noon!', 'The train left at noon.', 'the train left at noon.'],
      2, 'A statement (telling us a fact) ends with a full stop (.) and starts with a capital letter. 🚂'),
    grmQ('Which word is a VERB in "Sofia reads a book every night."?',
      ['Sofia', 'book', 'reads', 'night'],
      2, '"Reads" tells us what Sofia does — it is the action word (verb) in the sentence! 📚'),
    grmQ('Which word is a NOUN in "The shiny star twinkled."?',
      ['shiny', 'twinkled', 'star', 'the'],
      2, '"Star" is the naming word (noun) — it is the thing we are talking about! ⭐'),
    grmQ('Which sentence uses a FULL STOP and a QUESTION MARK correctly?',
      ['I like dogs? Do you like cats.', 'I like dogs. Do you like cats?', 'I like dogs. Do you like cats.', 'I like dogs? Do you like cats?'],
      1, '"I like dogs." is a statement (full stop). "Do you like cats?" is a question (question mark). ✅🐶🐱'),
    grmQ('Which word could go in the blank? "The ___ girl sang a song."',
      ['sang', 'quickly', 'sweet', 'and'],
      2, '"Sweet" is an adjective — it describes what the girl is like. Adjectives go before the noun they describe! 🎶'),
    grmQ('Which word is a CONJUNCTION?',
      ['dog', 'run', 'but', 'fast'],
      2, '"But" is a conjunction — it joins two parts of a sentence together! Conjunctions are joining words. 🔗'),
    grmQ('Which sentence has TWO nouns?',
      ['She ran quickly.', 'The boy ate a banana.', 'They jumped high.', 'He sang loudly.'],
      1, '"Boy" and "banana" are both nouns — one is a person, one is a thing! 👦🍌'),
    grmQ('Which word is an ADJECTIVE in "We saw a beautiful rainbow."?',
      ['saw', 'rainbow', 'we', 'beautiful'],
      3, '"Beautiful" tells us what the rainbow looks like — it is a describing word (adjective)! 🌈'),
    grmQ('Which word is a VERB in "The happy dog barked loudly."?',
      ['happy', 'dog', 'barked', 'loudly'],
      2, '"Barked" is the action word (verb) — it tells us what the dog did! 🐕'),
  ];
}

// ── Year 2 (Age 6–7) ────────────────────────────────────────
function grmYear2() {
  return [
    // ── Original 15 questions ──
    grmQ('What does an APOSTROPHE do in "I can\'t wait"?',
      ['Shows possession', 'Shows a list', 'Shows a missing letter (contraction)', 'Ends a sentence'],
      2, '"Can\'t" is short for "cannot". The apostrophe replaces the missing letter "no"! 📝'),
    grmQ('Which sentence uses "because" correctly?',
      ['I was late because I missed the bus.', 'Because I was late.', 'I was late, because.', 'Because late I was.'],
      0, '"Because" gives the reason for something and connects two clauses together! 🚌'),
    grmQ('Which word is an ADJECTIVE in this sentence? "The big, red ball rolled away."',
      ['ball', 'rolled', 'big', 'away'],
      2, '"Big" and "red" are adjectives — they describe what the ball looks like! 🔴'),
    grmQ('Which contraction is correct for "do not"?',
      ["don't", "do'nt", "dont'", "d'ont"],
      0, '"Don\'t" — the apostrophe replaces the "o" in "not". Do + not = don\'t! ✂️'),
    grmQ('Which sentence is punctuated correctly?',
      ['She asked, "Can I come?"', 'She asked "Can I come?"', 'She asked can i come?', 'she asked, can I come.'],
      0, 'Speech is wrapped in inverted commas (" "). A capital starts and a comma follows the speech tag! 💬'),
    grmQ('What is the PLURAL of "child"?',
      ['childs', 'childes', 'children', 'child\'s'],
      2, '"Children" is an irregular plural — it doesn\'t just add an "s". Learn it by heart! 👫'),
    grmQ('Which word is a VERB in "The rabbit hopped into the garden."?',
      ['rabbit', 'garden', 'hopped', 'into'],
      2, '"Hopped" is the verb — it tells us what the rabbit DID! 🐰'),
    grmQ('Which sentence is in the PAST TENSE?',
      ['She runs to school.', 'She is running to school.', 'She ran to school.', 'She will run to school.'],
      2, '"Ran" is past tense — it tells us the action has already happened. 🏃‍♀️'),
    grmQ('Which joining word shows CONTRAST? "I wanted cake ___ there was none left."',
      ['and', 'because', 'but', 'so'],
      2, '"But" shows a contrast between two ideas — you wanted cake BUT there was none! 🎂'),
    grmQ('Which sentence uses commas correctly in a list?',
      ['I bought apples oranges and bananas.', 'I bought apples, oranges and bananas.', 'I bought, apples, oranges, and, bananas.', 'I bought apples; oranges; and bananas.'],
      1, 'Commas separate items in a list. The last item uses "and" instead of a comma! 🍎🍊🍌'),
    grmQ('What does the apostrophe mean in "the cat\'s tail"?',
      ['The cat is missing', 'The tail belongs to the cat', 'Two cats', 'The cat was here'],
      1, 'An apostrophe + s shows possession — the tail BELONGS TO the cat! 🐱'),
    grmQ('Which is the CORRECT contraction for "she will"?',
      ["she'will", "sh'ell", "she'll", "shel'l"],
      2, '"She\'ll" — the apostrophe replaces "wi" in "will". She + will = she\'ll! 👩'),
    grmQ('Which sentence is in the PRESENT TENSE?',
      ['They played football.', 'They will play football.', 'They play football.', 'They had played football.'],
      2, '"Play" (present tense) tells us what is happening NOW or regularly! ⚽'),
    grmQ('Which word BEST completes: "She was ___ she had won the prize."?',
      ['sad because', 'delighted because', 'bored because', 'scared because'],
      1, '"Delighted because" makes the most sense — winning a prize makes you happy! 🏆'),
    grmQ('Which punctuation ends an EXCLAMATORY sentence?',
      ['Full stop (.)', 'Comma (,)', 'Question mark (?)', 'Exclamation mark (!)'],
      3, 'Exclamation marks (!) end sentences that show strong feelings or commands! 😮'),

    // ── New questions ──
    grmQ('Which is the CORRECT contraction for "I am"?',
      ["I'am", "Im'", "I'm", "Iam"],
      2, '"I\'m" — the apostrophe replaces the "a" in "am". I + am = I\'m! ✂️'),
    grmQ('Which sentence uses an APOSTROPHE FOR POSSESSION correctly?',
      ["the boys hat", "the boy's hat", "the boys' hat", "the boys hat's"],
      1, 'One boy owns the hat — add apostrophe + s after the owner\'s name: boy\'s hat! 🧢'),
    grmQ('Which sentence is in the FUTURE TENSE?',
      ['She danced all night.', 'She dances every Friday.', 'She will dance tomorrow.', 'She is dancing.'],
      2, '"Will dance" tells us about something that has NOT happened yet — it is in the future! 💃'),
    grmQ('Which word is an ADVERB in "He whispered quietly."?',
      ['He', 'whispered', 'quietly', 'the'],
      2, '"Quietly" tells us HOW he whispered — that makes it an adverb! Adverbs often end in -ly. 🤫'),
    grmQ('Which sentence uses a LIST with commas CORRECTLY?',
      ['I like swimming, cycling, and reading.', 'I like swimming cycling and reading.', 'I like, swimming, cycling, reading.', 'I like swimming; cycling; reading.'],
      0, 'Items in a list are separated by commas. The last item joins with "and". ✅🏊🚴📖'),
    grmQ('What is the contraction of "they are"?',
      ["they're", "their", "there", "they'ar"],
      0, '"They\'re" = they + are. The apostrophe replaces the "a". Don\'t mix it up with "their" or "there"! 👥'),
    grmQ('Which sentence uses the PAST TENSE correctly?',
      ['Yesterday, I go to the park.', 'Yesterday, I went to the park.', 'Yesterday, I will go to the park.', 'Yesterday, I going to the park.'],
      1, '"Went" is the past tense of "go" — it tells us the action already happened yesterday! 🌳'),
    grmQ('Which word is an ADVERB?',
      ['beautiful', 'gently', 'flower', 'and'],
      1, '"Gently" tells us HOW something was done — it is an adverb that describes a verb! 🌸'),
    grmQ('What does "can\'t" stand for?',
      ['can not', 'cannot', 'can it', 'could not'],
      1, '"Can\'t" is short for "cannot" — the apostrophe takes the place of the letters "no"! ✂️'),
    grmQ('Which sentence uses DIRECT SPEECH correctly?',
      ['"I am tired," said Zara.', '"I am tired" said Zara.', 'I am tired, said Zara.', '"I am tired" Said Zara.'],
      0, 'Direct speech: inverted commas around the words, comma inside, then lowercase "said". ✅'),
    grmQ('Which word shows the PAST TENSE of "run"?',
      ['runned', 'runs', 'ran', 'running'],
      2, '"Ran" is the past tense of "run" — irregular verbs change their whole spelling! 🏃'),
    grmQ('Which sentence uses COMMAS IN A LIST correctly?',
      ['We need pens, pencils, and rulers.', 'We need pens pencils and rulers.', 'We need, pens, pencils, and rulers.', 'We need pens pencils and, rulers.'],
      0, 'Commas separate each item in a list. Use "and" before the last item! 📝'),
    grmQ('Which is an ADVERB in "She smiled warmly at her friend."?',
      ['smiled', 'warmly', 'friend', 'she'],
      1, '"Warmly" is an adverb — it describes HOW she smiled. Adverbs tell us how, when, or where! 😊'),
    grmQ('Which contraction means "we have"?',
      ["we've", "we'have", "weve", "w'have"],
      0, '"We\'ve" = we + have. The apostrophe replaces the "ha" in "have". ✅'),
    grmQ('Which sentence uses the PRESENT TENSE to describe a HABIT?',
      ['She painted a picture.', 'She will paint a picture.', 'She paints pictures every day.', 'She has painted a picture.'],
      2, '"Paints every day" is present tense describing a habit or routine — something that happens regularly! 🎨'),
    grmQ('Which word has a SUFFIX added to make an ADVERB?',
      ['quick', 'quickly', 'quickness', 'quicken'],
      1, '"Quickly" = quick + ly. Adding "-ly" to an adjective usually makes an adverb! 🔤'),
    grmQ('Which sentence uses the APOSTROPHE FOR POSSESSION with a NAME correctly?',
      ["James hat is red.", "James' hat is red.", "Jameses hat is red.", "James's hat is red."],
      3, '"James\'s" — for names ending in "s", you can still add \'s. James\'s hat. ✅🧢'),
    grmQ('Which is NOT an adverb?',
      ['slowly', 'loudly', 'carefully', 'beautiful'],
      3, '"Beautiful" is an adjective (describing word). Adverbs often end in -ly but "beautiful" describes a noun, not a verb! 🌸'),
    grmQ('Which sentence uses BECAUSE to give a reason?',
      ['I was cold because I forgot my coat.', 'I was cold because.', 'Because I was cold.', 'I was cold, because warm.'],
      0, '"I was cold because I forgot my coat" — "because" links the effect (cold) to the cause (forgot coat). ✅🧥'),
    grmQ('Which is the correct PLURAL of "tooth"?',
      ['tooths', 'teeths', 'teeth', 'tooth\'s'],
      2, '"Teeth" is an irregular plural — it changes the whole word, not just adding an "s"! 🦷'),
    grmQ('Which word is a CONJUNCTION in "I like apples but not pears."?',
      ['like', 'apples', 'but', 'pears'],
      2, '"But" is the conjunction — it joins two ideas and shows contrast! 🍎'),
    grmQ('Which sentence uses an EXCLAMATION MARK correctly?',
      ['What time is it!', 'I ate my dinner!', 'Brilliant, I passed my test!', 'She, went home!'],
      2, '"Brilliant, I passed my test!" expresses genuine excitement — perfect for an exclamation mark! 🎉'),
    grmQ('In "The teacher\'s desk is tidy," what does the apostrophe show?',
      ['A missing letter', 'The desk belongs to the teacher', 'There are many teachers', 'A contraction'],
      1, 'Teacher\'s desk — the apostrophe + s shows the desk BELONGS TO the teacher. This is possession! 👩‍🏫'),
    grmQ('Which word in "The children played happily." is an ADVERB?',
      ['children', 'played', 'happily', 'the'],
      2, '"Happily" tells us HOW the children played — that is what adverbs do! 😃'),
    grmQ('Which sentence correctly uses "were" for the past tense?',
      ['We was at the park.', 'We were at the park.', 'We is at the park.', 'We are at the park yesterday.'],
      1, '"We were" is the correct past tense. "Was" is used with I/he/she/it, "were" with we/you/they! ✅'),
    grmQ('Which correctly uses a COMMA after a time phrase at the start?',
      ['After school we had dinner.', 'After school, we had dinner.', 'After, school we had dinner.', 'After school we, had dinner.'],
      1, 'When a time phrase (like "After school") starts the sentence, a comma follows it! ✅🍽️'),
    grmQ('Which sentence correctly uses an APOSTROPHE in a contraction?',
      ["It is hot today. = Its hot today.", "It is hot today. = It's hot today.", "It is hot today. = Its' hot today.", "It is hot today. = It'is hot today."],
      1, '"It\'s" = it + is. The apostrophe replaces the "i" in "is". Don\'t confuse with "its" (belonging to it)! ☀️'),
    grmQ('Which is the correct PAST TENSE of "see"?',
      ['seed', 'saw', 'seen', 'seened'],
      1, '"Saw" is the simple past tense of "see". Irregular verbs change shape: see → saw! 👀'),
    grmQ('Which word is an ADVERB in "The cat crept silently into the room."?',
      ['cat', 'crept', 'silently', 'room'],
      2, '"Silently" tells us HOW the cat crept — it is an adverb describing the verb "crept"! 🐱'),
  ];
}

// ── Year 3 (Age 7–8) ────────────────────────────────────────
function grmYear3() {
  return [
    // ── Original 15 questions ──
    grmQ('Which sentence uses a FRONTED ADVERBIAL correctly?',
      ['After lunch, we played outside.', 'We played outside, after lunch.', 'After lunch we played outside.', 'We, after lunch, played outside.'],
      0, 'A fronted adverbial starts the sentence and is followed by a COMMA. "After lunch," sets the scene! ⏰'),
    grmQ('Which word is a PREPOSITION in "The cat sat under the table"?',
      ['cat', 'sat', 'under', 'table'],
      2, '"Under" is a preposition — it shows WHERE the cat was in relation to the table! 🐱'),
    grmQ('Which conjunction shows TIME?',
      ['but', 'because', 'while', 'or'],
      2, '"While" is a time conjunction — "I ate while watching TV." It says two things happen at the same time! ⏱️'),
    grmQ('Which sentence uses INVERTED COMMAS correctly?',
      ['"I love books", said Maya.', '"I love books," said Maya.', 'I love books, said Maya.', '"I love books" said Maya.'],
      1, 'A comma comes INSIDE the closing inverted comma before the speech tag. "..," said Maya. 📖'),
    grmQ('Which word is an ADVERB in "She ran quickly to the door"?',
      ['ran', 'quickly', 'door', 'she'],
      1, '"Quickly" is an adverb — it describes HOW she ran. Adverbs often end in -ly! 🚀'),
    grmQ('Which sentence has a SUBORDINATE CLAUSE?',
      ['The dog barked.', 'The dog barked loudly.', 'Although it was raining, we went out.', 'We went out and had fun.'],
      2, '"Although it was raining" is a subordinate clause — it cannot stand alone but adds meaning! 🌧️'),
    grmQ('Which is the correct POSSESSIVE apostrophe for multiple dogs?',
      ["the dog's collar", "the dogs' collars", "the dogs collar", "the dogs's collars"],
      1, 'For plurals ending in "s", the apostrophe goes AFTER the s: dogs\' collars! 🐕'),
    grmQ('What does the prefix "un-" mean in "unhappy"?',
      ['Very happy', 'Not happy', 'A little happy', 'Always happy'],
      1, 'The prefix "un-" means NOT. Un + happy = not happy! 😔'),
    grmQ('Which sentence has a CONJUNCTION that shows REASON?',
      ['I ran because I was late.', 'I ran and I was late.', 'I ran while I was late.', 'I ran but I was late.'],
      0, '"Because" gives the reason — it explains WHY you ran. I ran BECAUSE I was late! 🏃'),
    grmQ('Which word is an ABSTRACT NOUN?',
      ['table', 'dog', 'happiness', 'London'],
      2, '"Happiness" is an abstract noun — it\'s something you feel, not touch or see! 😊'),
    grmQ('Which sentence uses the PRESENT PERFECT tense?',
      ['She runs every day.', 'She ran yesterday.', 'She has run three miles.', 'She will run tomorrow.'],
      2, '"Has run" is present perfect — the action happened recently and affects the present! 🏅'),
    grmQ('Which uses DIRECT SPEECH correctly?',
      ['Tom said he was hungry.', '"I am hungry," said Tom.', '"I am hungry" said Tom.', '"i am hungry," said Tom.'],
      1, 'Direct speech: inverted commas, comma inside, capital letter starts the speech. ✅'),
    grmQ('Which word is a NOUN PHRASE modifier in "the enormous grey elephant"?',
      ['elephant', 'enormous grey', 'the', 'enormous'],
      1, '"Enormous grey" are adjectives that modify (describe) the noun "elephant" as a phrase! 🐘'),
    grmQ('Which is a COMPOUND SENTENCE?',
      ['The bird flew.', 'The bird flew swiftly over the trees.', 'The bird flew and the cat watched.', 'Because the bird flew.'],
      2, 'A compound sentence joins two independent clauses with a conjunction like "and"! 🐦🐱'),
    grmQ('Which suffix changes "hope" into an adjective?',
      ['-ing', '-ful', '-ed', '-er'],
      1, '"Hopeful" — the suffix "-ful" turns the noun/verb "hope" into an adjective meaning full of hope! 🌟'),

    // ── New questions ──
    grmQ('Which fronted adverbial CORRECTLY sets the time at the start?',
      ['Early in the morning the birds sang.', 'Early in the morning, the birds sang.', 'The birds sang, early in the morning.', 'Early, in the morning the birds sang.'],
      1, '"Early in the morning," is a fronted adverbial — it must be followed by a comma! ✅🐦'),
    grmQ('Which word is a PREPOSITION in "She hid behind the tree."?',
      ['she', 'hid', 'behind', 'tree'],
      2, '"Behind" is a preposition — it tells us WHERE she was in relation to the tree! 🌳'),
    grmQ('What does the prefix "dis-" mean in "disagree"?',
      ['To agree fully', 'Not to agree', 'To agree sometimes', 'To agree again'],
      1, '"Dis-" means NOT or the opposite. Dis + agree = to NOT agree! 🙅'),
    grmQ('Which is an ABSTRACT NOUN?',
      ['dog', 'courage', 'chair', 'river'],
      1, '"Courage" is an abstract noun — it is a quality or feeling you cannot physically touch! 🦁'),
    grmQ('Which sentence uses the PRESENT PERFECT tense?',
      ['I eat my lunch.', 'I ate my lunch.', 'I have eaten my lunch.', 'I will eat my lunch.'],
      2, '"Have eaten" = present perfect. It uses "have/has" + past participle to link past to present! 🍱'),
    grmQ('Which sentence has a FRONTED ADVERBIAL showing PLACE?',
      ['In the dark forest, the wolf howled.', 'The wolf howled in the dark forest.', 'The wolf, in the forest, howled.', 'Howled the wolf, in the forest.'],
      0, '"In the dark forest," is a fronted adverbial of place — it tells us WHERE, and is followed by a comma! 🐺🌲'),
    grmQ('Which word is a SUBORDINATING CONJUNCTION?',
      ['and', 'but', 'or', 'although'],
      3, '"Although" introduces a subordinate clause — it connects a dependent idea to the main clause! 🔗'),
    grmQ('Which sentence has a CORRECTLY punctuated subordinate clause?',
      ['Because she studied hard she passed.', 'Because she studied hard, she passed.', 'She passed, because, she studied hard.', 'She passed because, she studied hard.'],
      1, 'When the subordinate clause comes FIRST, a comma separates it from the main clause! ✅📚'),
    grmQ('Which is the CORRECT use of inverted commas?',
      ['"Come here!" called Mum.', '"Come here"! called Mum.', '"Come here" called Mum!', 'Come here!" called Mum.'],
      0, 'The exclamation mark goes INSIDE the closing inverted comma: "Come here!" Then "called Mum." ✅'),
    grmQ('What does the suffix "-ness" do in "darkness"?',
      ['Makes it a verb', 'Makes it an adjective', 'Makes it a noun', 'Makes it an adverb'],
      2, 'Adding "-ness" to an adjective makes a noun: dark + ness = darkness (a state or quality)! 🌑'),
    grmQ('Which sentence uses a PREPOSITION correctly?',
      ['The fish swam over the pond.', 'The fish swam over.', 'Over swam the fish.', 'The fish over the swam pond.'],
      0, '"Over the pond" — "over" is the preposition showing WHERE the fish swam! 🐟'),
    grmQ('What is the PRESENT PERFECT tense of "write"?',
      ['I write', 'I wrote', 'I have written', 'I will write'],
      2, '"I have written" is the present perfect — formed with "have" + past participle "written"! ✍️'),
    grmQ('Which word has the prefix "re-" correctly used?',
      ['rebuild', 'recat', 'retable', 'refunny'],
      0, '"Re-" means to do again: rebuild (build again). Only real words can have prefixes added! 🔨'),
    grmQ('Which is a CONCRETE noun?',
      ['freedom', 'love', 'bridge', 'imagination'],
      2, '"Bridge" is a concrete noun — it is a physical thing you can see and touch! 🌉'),
    grmQ('Which sentence uses BECAUSE to give the cause?',
      ['She cried because she had lost her toy.', 'She cried, because.', 'Because sad she was.', 'She cried because.'],
      0, '"Because she had lost her toy" explains WHY she cried — "because" introduces the reason! 😢'),
    grmQ('Which is a TIME ADVERBIAL?',
      ['On top of the hill', 'Before breakfast', 'Running quickly', 'The tall man'],
      1, '"Before breakfast" tells us WHEN something happened — it is a time adverbial! ⏰🥣'),
    grmQ('Which sentence has INVERTED COMMAS in the WRONG place?',
      ['"Let\'s go," said Dan.', '"Let\'s go," said Dan.', 'Dan said, "Let\'s go."', '"Let\'s go" said Dan.'],
      3, '"Let\'s go" said Dan — the comma should be INSIDE the inverted commas: "Let\'s go," said Dan. ✅'),
    grmQ('Which word has the suffix "-ly" making an ADVERB?',
      ['careful', 'carefully', 'careless', 'carer'],
      1, '"Carefully" = careful + ly. The suffix "-ly" turns the adjective into an adverb! 🔤'),
    grmQ('What does the prefix "mis-" mean in "misunderstand"?',
      ['Again', 'Not correctly', 'Very much', 'Before'],
      1, '"Mis-" means wrongly or not correctly: misunderstand = to understand wrongly! 🤔'),
    grmQ('Which sentence uses WHILE correctly as a time conjunction?',
      ['She sang while.', 'While she sang happy.', 'She sang while she cooked dinner.', 'While sang she cooked.'],
      2, '"While" connects two simultaneous actions: she sang AND cooked at the same time! 🎵🍳'),
    grmQ('Which word is a PREPOSITION in "He jumped over the fence."?',
      ['jumped', 'over', 'fence', 'he'],
      1, '"Over" is a preposition — it shows the relationship between the jump and the fence! 🤸'),
    grmQ('Which sentence correctly uses an ADVERB at the START?',
      ['Suddenly, the lights went out.', 'Suddenly the lights, went out.', 'The lights went suddenly, out.', 'Suddenly went the lights out.'],
      0, '"Suddenly," at the start is a fronted adverb — followed by a comma and then the main clause! 💡'),
    grmQ('Which suffix makes a word mean "full of"?',
      ['-less', '-ful', '-ing', '-ment'],
      1, '"Wonderful" = wonder + ful. The suffix "-ful" means "full of" something! 🌟'),
    grmQ('Which sentence uses DIRECT SPEECH with the CORRECT capital letter inside the speech marks?',
      ['"the dog is missing," she cried.', '"The dog is missing," she cried.', '"The Dog is missing," she cried.', '"The dog Is missing," she cried.'],
      1, 'The first word inside inverted commas starts with a capital letter, but not other words! ✅🐕'),
    grmQ('Which is the CORRECT use of an APOSTROPHE in a plural possessive?',
      ["the girl's bikes (one girl)", "the girls' bikes (many girls)", "the girls bike's", "the girl's bikes (many girls)"],
      1, 'Many girls → girls. Add apostrophe AFTER the s: girls\' bikes. The bikes belong to multiple girls! 🚲'),
    grmQ('Which word is an ABSTRACT NOUN?',
      ['mountain', 'kindness', 'bicycle', 'teacher'],
      1, '"Kindness" is an abstract noun — it is a quality or idea you cannot physically touch or see! 💛'),
    grmQ('Which sentence uses ALTHOUGH correctly?',
      ['Although it was cold.', 'Although it was cold, we swam.', 'We swam although.', 'Although we cold swam.'],
      1, '"Although it was cold, we swam." The subordinate clause (Although...) is followed by a comma, then main clause! 🏊❄️'),
    grmQ('What is the PRESENT PERFECT of "go"?',
      ['I go', 'I went', 'I have gone', 'I going'],
      2, '"I have gone" is present perfect: have + past participle (gone). Links a past action to now! 🚶'),
    grmQ('Which sentence uses a TIME FRONTED ADVERBIAL correctly?',
      ['Every morning, she brushes her teeth.', 'She, every morning, brushes her teeth.', 'Every morning she brushes her teeth.', 'She brushes her teeth, every morning.'],
      0, '"Every morning," is a fronted adverbial followed by a comma — then the main clause! ✅🦷'),
  ];
}

// ── Year 4 (Age 8–9) ────────────────────────────────────────
function grmYear4() {
  return [
    // ── Original 15 questions ──
    grmQ('Which sentence uses a RELATIVE CLAUSE correctly?',
      ['The girl, which was clever, won the prize.', 'The girl who was clever won the prize.', 'The girl that she was clever won the prize.', 'The girl clever won the prize.'],
      1, '"Who" introduces relative clauses for people. "The girl who was clever" tells us more about the girl! 🏆'),
    grmQ('Which sentence uses BRACKETS correctly?',
      ['The Amazon (the world\'s largest river) flows through Brazil.', 'The Amazon, the world\'s largest river flows through Brazil.', 'The Amazon the world\'s largest river flows through Brazil.', '(The Amazon) the world\'s largest river flows through Brazil.'],
      0, 'Brackets ( ) add extra information that could be removed without changing the main meaning! 🌊'),
    grmQ('Which word is a PRONOUN in "She gave him the book"?',
      ['gave', 'book', 'She', 'the'],
      2, '"She" and "him" are pronouns — they replace nouns (names) to avoid repetition! 📚'),
    grmQ('Which sentence uses a FRONTED ADVERBIAL correctly?',
      ['Slowly, the tortoise crossed the line.', 'The tortoise, slowly, crossed the line.', 'The tortoise crossed, slowly, the line.', 'The tortoise crossed the line slowly,'],
      0, '"Slowly," fronted adverbial + comma, then the main clause. Sets the manner of the action! 🐢'),
    grmQ('Which sentence is in the PASSIVE VOICE?',
      ['The chef cooked the meal.', 'The meal was cooked by the chef.', 'The chef is cooking.', 'The meal cooked itself.'],
      1, 'Passive voice: the object becomes the subject. "The meal was cooked" — the meal is the focus! 🍽️'),
    grmQ('Which correctly uses INVERTED COMMAS for speech?',
      ['"Run!" shouted the coach.', 'Run! shouted the coach.', '"Run" shouted the coach!', '"Run!" Shouted the coach.'],
      0, 'After "Run!" the speech mark closes, then lowercase "shouted". ✅'),
    grmQ('What is the function of a COLON (:)?',
      ['To join two sentences together', 'To introduce a list or explanation', 'To show possession', 'To replace a full stop'],
      1, 'A colon (:) introduces a list or explanation: it says "here comes more detail"! 📋'),
    grmQ('Which word is a MODAL VERB?',
      ['run', 'could', 'happy', 'table'],
      1, '"Could" is a modal verb — it shows possibility or ability. Could, would, should, might, can! 💭'),
    grmQ('Which sentence uses DASHES correctly for parenthesis?',
      ['The match — which was brilliant — ended in a draw.', 'The match — which was brilliant ended in a draw.', 'The match which was brilliant — ended in a draw.', 'The match — which was brilliant,— ended in a draw.'],
      0, 'Dashes come in pairs to add extra information — just like brackets! ⚽'),
    grmQ('Which sentence contains a SUBORDINATE CLAUSE introduced by "although"?',
      ['Although she tried hard.', 'Although she tried hard, she did not win.', 'She tried hard, although.', 'She tried, hard although.'],
      1, '"Although she tried hard" is subordinate — it cannot stand alone. It depends on the main clause! 💪'),
    grmQ('What does a SEMI-COLON (;) do?',
      ['Ends a sentence', 'Links two related independent clauses without a conjunction', 'Shows possession', 'Introduces a list after a colon'],
      1, 'A semi-colon links two closely related sentences: "I studied hard; I passed the test." 📝'),
    grmQ('Which is a COMPLEX SENTENCE?',
      ['The cat sat.', 'The cat sat and slept.', 'When it rained, the cat stayed inside.', 'The cat: sat and slept.'],
      2, 'A complex sentence has a main clause + a subordinate clause. "When it rained" is subordinate! 🌧️🐱'),
    grmQ('Which sentence uses the PERFECT TENSE correctly?',
      ['She eat all her dinner.', 'She has eaten all her dinner.', 'She eating all her dinner.', 'She eats all her dinner yesterday.'],
      1, '"Has eaten" is the present perfect — formed with "have/has" + past participle. 🍴'),
    grmQ('Which is a POSSESSIVE PRONOUN?',
      ['he', 'them', 'theirs', 'who'],
      2, '"Theirs" is a possessive pronoun — it shows ownership without naming the noun. Mine, yours, his, hers, ours, theirs! 🔑'),
    grmQ('Which correctly uses a COMMA after a fronted adverbial?',
      ['After the storm the rainbow appeared.', 'After the storm, the rainbow appeared.', 'After the storm; the rainbow appeared.', 'After the storm: the rainbow appeared.'],
      1, 'A fronted adverbial MUST be followed by a comma before the main clause. ✅🌈'),

    // ── New questions ──
    grmQ('Which sentence uses a RELATIVE CLAUSE with "which"?',
      ['The book, which I borrowed, was fantastic.', 'The book, who I borrowed, was fantastic.', 'The book that I borrowed it was fantastic.', 'The book was fantastic which I borrowed.'],
      0, '"Which" introduces relative clauses for things (not people). Commas wrap the extra information! 📖'),
    grmQ('Which sentence uses a RELATIVE CLAUSE with "that"?',
      ['The dog that bit me is friendly now.', 'The dog, that bit me, is friendly now.', 'The dog which bit me it is friendly now.', 'The dog friendly that bit me.'],
      0, '"That" introduces a defining relative clause — it is essential to the meaning and has no commas! 🐕'),
    grmQ('Which sentence uses BRACKETS FOR PARENTHESIS correctly?',
      ['The capital city (London) is in the south of England.', 'The capital city London() is in the south.', '(The capital city) London is in the south.', 'The capital city is (in the south) London.'],
      0, 'Brackets add extra info: (London) tells us the capital city\'s name without breaking the flow! 🏙️'),
    grmQ('Which sentence is in the PASSIVE voice?',
      ['The pupils tidied the classroom.', 'The classroom was tidied by the pupils.', 'The pupils are tidying.', 'The classroom needs tidying.'],
      1, '"Was tidied by the pupils" — the classroom (object) becomes the subject. That\'s passive voice! 🏫'),
    grmQ('Which is the ACTIVE voice version of "The window was broken by the ball"?',
      ['The window broke itself.', 'The ball broke the window.', 'The broken window was a ball.', 'The ball was breaking.'],
      1, 'Active: subject (ball) + verb (broke) + object (window). The ball DID the action! 🏀'),
    grmQ('Which word is a MODAL VERB showing OBLIGATION?',
      ['run', 'might', 'must', 'quickly'],
      2, '"Must" is a modal verb showing strong obligation. "You must wear a seatbelt." 🚗'),
    grmQ('Which sentence uses a COLON to introduce an EXPLANATION?',
      ['She was nervous: she had never performed before.', 'She was nervous, she had never performed before.', 'She was nervous. She had never: performed before.', 'She was: nervous she had never performed before.'],
      0, 'A colon can introduce an explanation or reason: what comes after explains what comes before! ✅🎭'),
    grmQ('Which sentence uses a SEMI-COLON correctly?',
      ['The sky was grey; rain was coming.', 'The sky was grey, rain was coming.', 'The sky was grey: rain was coming.', 'The sky was grey; and rain was coming.'],
      0, 'A semi-colon joins two related independent clauses. No conjunction needed! ☁️🌧️'),
    grmQ('What does "relative clause" do in a sentence?',
      ['It replaces the main verb', 'It adds information about a noun', 'It starts the sentence', 'It shows tense'],
      1, 'A relative clause gives extra information about a noun: "The boy WHO won is my friend." 📝'),
    grmQ('Which sentence uses DASHES for parenthesis INCORRECTLY?',
      ['My sister — who is eight — loves dancing.', 'My sister — who is eight loves dancing.', 'My sister — who is eight — loves dancing.', 'The match — played on Friday — was exciting.'],
      1, 'Dashes for parenthesis MUST come in pairs: one before AND one after the extra information! ❌'),
    grmQ('Which correctly uses a MODAL VERB to suggest POSSIBILITY?',
      ['She will come to the party.', 'She might come to the party.', 'She must come to the party.', 'She shall come to the party.'],
      1, '"Might" suggests possibility — she may or may not come. It is not certain! 🎉'),
    grmQ('Which CORRECTLY uses "whose" in a relative clause?',
      ['The artist, whose paintings are famous, won an award.', 'The artist, which paintings are famous, won an award.', 'The artist, who paintings are famous, won an award.', 'The artist whose won an award.'],
      0, '"Whose" shows belonging in a relative clause — "whose paintings" = the paintings belong to the artist! 🎨'),
    grmQ('Which is the CORRECT use of BRACKETS in this sentence?',
      ['My dog (a Labrador) loves swimming.', 'My dog a Labrador) loves swimming.', '(My dog a Labrador loves swimming.', 'My (dog a Labrador) loves swimming.'],
      0, 'Brackets must come in pairs and wrap the extra detail completely: (a Labrador). ✅🐾'),
    grmQ('Which sentence uses a COLON before a LIST correctly?',
      ['I need: eggs, milk, and butter.', 'I need to buy the following: eggs, milk, and butter.', 'I need: eggs; milk; butter.', 'I need eggs: milk and butter.'],
      1, 'A colon introduces a list when the clause before it is COMPLETE: "I need the following:" ✅🛒'),
    grmQ('Which sentence shows PARENTHESIS using COMMAS?',
      ['The headteacher, who retired last year, was very popular.', 'The headteacher who retired last year was very popular.', 'The headteacher was, very popular, retired last year.', 'The headteacher retired, last year, who was popular.'],
      0, 'Commas can mark parenthesis — the extra info (who retired last year) is wrapped in commas! 👩‍💼'),
    grmQ('Which is a SUBORDINATING conjunction?',
      ['and', 'but', 'because', 'or'],
      2, '"Because" is a subordinating conjunction — it introduces a subordinate clause that depends on the main clause! 🔗'),
    grmQ('Which sentence uses a RELATIVE PRONOUN correctly?',
      ['The woman which lives next door is a doctor.', 'The woman who lives next door is a doctor.', 'The woman that she lives next door is a doctor.', 'The woman whose lives next door is a doctor.'],
      1, '"Who" is used for people: "The woman who lives next door." Use "which" for things! 👩‍⚕️'),
    grmQ('Which is the CORRECT semi-colon use between TWO related facts?',
      ['Jake loves football, he plays every weekend.', 'Jake loves football; he plays every weekend.', 'Jake loves football: he plays every weekend.', 'Jake loves football — he plays every weekend.'],
      1, 'A semi-colon joins two closely related independent clauses without a conjunction. ✅⚽'),
    grmQ('Which modal verb shows the WEAKEST possibility?',
      ['will', 'must', 'shall', 'might'],
      3, '"Might" shows the weakest possibility — it is uncertain. "Will" and "shall" show certainty! 🎲'),
    grmQ('What type of clause is "which I had borrowed" in "The book, which I had borrowed, was overdue"?',
      ['A main clause', 'A fronted adverbial', 'A relative clause', 'A noun clause'],
      2, '"Which I had borrowed" gives more information about the book — it is a relative clause! 📚'),
    grmQ('Which sentence uses a DASH for a dramatic pause?',
      ['She reached for the handle — it was gone.', 'She reached for the handle, it was gone.', 'She reached for the handle: it was gone.', 'She reached for the handle. It, was gone.'],
      0, 'A single dash creates a dramatic pause before a reveal or surprise! 😮'),
    grmQ('Which sentence correctly uses the PRESENT PERFECT with "have"?',
      ['They have went to the shops.', 'They have gone to the shops.', 'They has gone to the shops.', 'They have go to the shops.'],
      1, '"Have gone" — present perfect uses "have/has" + PAST PARTICIPLE. "Went" is simple past, not a past participle! 🛒'),
    grmQ('Which sentence uses COMMAS for parenthesis with a relative clause?',
      ['The film which was brilliant was very long.', 'The film, which was brilliant, was very long.', 'The film, which was brilliant was very long.', 'The film which was brilliant, was very long.'],
      1, 'A non-defining relative clause is wrapped in commas: one before "which" and one after the clause! 🎬'),
    grmQ('Which word introduces a RELATIVE CLAUSE about a THING (not a person)?',
      ['who', 'whose', 'whom', 'which'],
      3, '"Which" introduces relative clauses about things and animals. "Who" is used for people! 🔑'),
    grmQ('Which correctly shows PARENTHESIS with DASHES?',
      ['The winner — a year 5 pupil — received a gold medal.', 'The winner a year 5 pupil — received a gold medal.', 'The winner — a year 5 pupil received a gold medal.', 'The winner — a year 5 — pupil received a gold medal.'],
      0, 'Both dashes must be in place to wrap the parenthetical information! The winner — a year 5 pupil — ✅🥇'),
    grmQ('What does the PASSIVE VOICE emphasise compared to the ACTIVE VOICE?',
      ['The person doing the action', 'The action or the thing receiving it', 'The time of the action', 'The number of nouns'],
      1, 'The passive voice shifts focus to WHAT happened or who was affected, rather than who did it! 🔄'),
    grmQ('Which sentence uses "could" as a MODAL VERB correctly?',
      ['She could swims very fast.', 'She could swim very fast.', 'She could swam very fast.', 'She could swimming very fast.'],
      1, 'Modal verbs like "could" are followed by the BASE form of the verb: could + swim (not swims/swam/swimming)! 🏊'),
    grmQ('Which sentence has a CORRECTLY placed FRONTED ADVERBIAL?',
      ['Quietly and carefully, she opened the door.', 'Quietly and carefully she, opened the door.', 'She opened, quietly and carefully, the door.', 'She opened the door quietly, and carefully.'],
      0, '"Quietly and carefully," is the fronted adverbial — it must be followed immediately by a comma! 🚪'),
    grmQ('Which is an example of PARENTHESIS that adds a FACT?',
      ['The Nile (the world\'s longest river) flows through Egypt.', 'The Nile flows through Egypt.', 'The Nile, which is long, and flows through Egypt.', '(The Nile flows through Egypt).'],
      0, 'Brackets add a helpful fact — (the world\'s longest river) tells us more without breaking the sentence! 🌍'),
  ];
}

// ── Year 5 (Age 9–10) ───────────────────────────────────────
function grmYear5() {
  return [
    // ── Original 15 questions ──
    grmQ('Which sentence uses a RELATIVE CLAUSE with "whose"?',
      ['The student, who won, was happy.', 'The student whose work was best won the prize.', 'The student which won was happy.', 'The student won, who was happy.'],
      1, '"Whose" introduces relative clauses showing belonging — "whose work" refers to the student\'s work! 🏆'),
    grmQ('Which sentence is in the PASSIVE VOICE?',
      ['Scientists discovered a new planet.', 'A new planet was discovered by scientists.', 'Scientists are discovering planets.', 'A planet scientists discovered.'],
      1, 'Passive: object (planet) becomes subject, and the agent (scientists) follows "by". 🔭'),
    grmQ('Which sentence uses a MODAL VERB to show CERTAINTY?',
      ['She might come.', 'She must come.', 'She could come.', 'She may come.'],
      1, '"Must" shows near certainty. Might, could, may show possibility; must shows you\'re sure! ✅'),
    grmQ('Which correctly uses PARENTHESIS with commas?',
      ['My teacher, who is very kind gave me extra help.', 'My teacher, who is very kind, gave me extra help.', 'My teacher who, is very kind, gave me extra help.', 'My teacher who is very kind gave me extra help.'],
      1, 'Parenthesis with commas: a pair of commas wraps the extra information. Both needed! 👩‍🏫'),
    grmQ('Which is the SUBJUNCTIVE MOOD?',
      ['If I was you, I would study.', 'If I were you, I would study.', 'If I am you, I would study.', 'If I is you, I would study.'],
      1, '"If I were you" — the subjunctive uses "were" for ALL pronouns in formal/hypothetical clauses! 🎓'),
    grmQ('What is the effect of using a SHORT sentence after long ones?',
      ['It shows the writer has run out of ideas', 'It creates emphasis and impact', 'It is a grammar mistake', 'It makes the text too informal'],
      1, 'Short sentences create IMPACT. They stand out. They are powerful! ⚡'),
    grmQ('Which uses a COLON correctly to introduce a list?',
      ['She needed: pencil, ruler, and eraser.', 'She needed a pencil, ruler, and eraser.', 'She needed the following: a pencil, a ruler, and an eraser.', 'She needed — pencil, ruler, and eraser.'],
      2, '"She needed the following:" — the colon follows a complete clause, then introduces the list! ✏️'),
    grmQ('Which sentence uses a HYPHEN correctly?',
      ['A well known author visited our school.', 'A well-known author visited our school.', 'A well known-author visited our school.', 'A well known author, visited our school.'],
      1, 'Hyphens join compound adjectives before a noun: "well-known author". Without the noun, no hyphen needed! ✍️'),
    grmQ('Which is FORMAL language?',
      ['Kids should get more time off.', 'Students would benefit from additional recreational time.', 'We want more play time, yeah?', 'More play would be well good.'],
      1, 'Formal language: precise vocabulary, full sentences, no slang. For official writing! 🎩'),
    grmQ('Which sentence uses ELLIPSIS (...) correctly?',
      ['She opened the door...', 'She opened...the door...', '...opened she the door.', 'She opened the door.…'],
      0, 'Ellipsis creates tension or shows something is left unsaid. "She opened the door..." — what\'s next? 😮'),
    grmQ('What is a RELATIVE PRONOUN?',
      ['I, you, he, she', 'who, which, that, whose, whom', 'might, could, should', 'and, but, or'],
      1, 'Relative pronouns introduce relative clauses: who (people), which (things), that (either), whose (possession)! 🔗'),
    grmQ('Which correctly uses SEMI-COLONS in a complex list?',
      ['We visited Paris, France; Rome, Italy; and Berlin, Germany.', 'We visited Paris, France, Rome, Italy, and Berlin, Germany.', 'We visited Paris France; Rome Italy; Berlin Germany.', 'We visited: Paris, France; Rome, Italy; Berlin, Germany.'],
      0, 'Semi-colons separate items in a list when the items themselves contain commas! 🌍'),
    grmQ('Which sentence demonstrates PATHETIC FALLACY?',
      ['She was sad.', 'The dark clouds mirrored her gloomy mood.', 'It rained a lot.', 'She cried at the window.'],
      1, 'Pathetic fallacy uses weather/nature to reflect a character\'s emotions. Dark clouds = gloomy mood! 🌧️'),
    grmQ('Which modal verb shows POSSIBILITY (not certainty)?',
      ['will', 'must', 'shall', 'might'],
      3, '"Might" shows possibility — it may or may not happen. Will/shall = certainty, must = strong obligation! 🎲'),
    grmQ('What does the prefix "inter-" mean in "international"?',
      ['Inside', 'Against', 'Between or among', 'Before'],
      2, '"Inter-" means between or among: international (between nations), interact, interview! 🌐'),

    // ── New questions ──
    grmQ('Which sentence uses the SUBJUNCTIVE correctly after "I suggest"?',
      ['I suggest that she goes home.', 'I suggest that she go home.', 'I suggest that she went home.', 'I suggest that she has gone home.'],
      1, 'In the subjunctive mood after "suggest/recommend/insist", use the BASE form: "she go" (not goes)! 🎓'),
    grmQ('Which sentence is FORMAL?',
      ['Loads of people think it\'s a great idea.', 'It is widely regarded as an excellent initiative.', 'Everybody reckons it\'s brilliant.', 'It\'s pretty good, to be honest.'],
      1, 'Formal writing uses complex vocabulary and avoids contractions and colloquial phrases! 📄'),
    grmQ('Which is INFORMAL language?',
      ['I would be grateful if you could assist.', 'The results were outstanding.', 'Could you let us know as soon as possible?', 'It was dead good, honestly!'],
      3, '"Dead good, honestly!" uses slang and is informal — fine for chatting, not for formal writing! 💬'),
    grmQ('Which sentence uses a HYPHEN to avoid ambiguity?',
      ['She is a little used car dealer.', 'She is a little-used car dealer.', 'She is a little, used car dealer.', 'She is a little used-car dealer.'],
      1, '"Little-used" means "rarely used" — the hyphen joins the compound adjective before the noun! 🚗'),
    grmQ('What does ELLIPSIS (...) suggest when used in narrative writing?',
      ['The sentence is finished', 'A pause, hesitation, or something left unsaid', 'A list is coming', 'It is a mistake'],
      1, 'Ellipsis (...) creates a dramatic pause or hints that something was omitted or trails off... 😶'),
    grmQ('Which sentence uses SEMI-COLONS in a complex list correctly?',
      ['For the trip, bring a water bottle; a warm coat; and a packed lunch.', 'For the trip bring: a water bottle a warm coat a packed lunch.', 'Bring, a water bottle; warm coat; packed lunch.', 'Bring: a water bottle, a warm coat, a packed lunch.'],
      0, 'When list items are long or contain commas, semi-colons separate them clearly! ✅🎒'),
    grmQ('Which is an example of PATHETIC FALLACY?',
      ['He walked down the road.', 'The howling wind mourned his departure.', 'She left the house.', 'It was windy that day.'],
      1, 'Pathetic fallacy: "howling wind mourned" — the weather reflects the emotion. The wind feels the sadness! 🌬️'),
    grmQ('Which sentence correctly uses a HYPHEN in a compound NOUN?',
      ['fire fly', 'fire-fly', 'firefily', 'fire: fly'],
      1, 'Hyphens can link two words to form a compound noun: fire-fly. Some become one word over time! 🌟'),
    grmQ('What is the effect of using VARIED SENTENCE OPENINGS in writing?',
      ['It confuses the reader', 'It creates rhythm and keeps the reader interested', 'It always makes sentences longer', 'It is always incorrect'],
      1, 'Varying sentence openings (adverbials, subordinate clauses, nouns, verbs) adds rhythm and engagement! ✍️'),
    grmQ('Which sentence uses the PASSIVE VOICE to focus on WHAT happened?',
      ['The vandal broke the window.', 'The window was broken.', 'Someone broke the window.', 'Breaking the window was wrong.'],
      1, '"The window was broken" — passive voice hides the agent and focuses on the event itself! 🪟'),
    grmQ('Which sentence uses a RELATIVE PRONOUN correctly?',
      ['The scientist who discovered penicillin won the Nobel Prize.', 'The scientist which discovered penicillin won the Nobel Prize.', 'The scientist that he discovered penicillin won.', 'The scientist whose discovered penicillin won.'],
      0, '"Who" is the correct relative pronoun for a person. "Which" is for things! 🔬'),
    grmQ('Which correctly uses FORMAL language in a letter opening?',
      ['Hey, just writing to say...', 'Hiya! I\'m writing because...', 'Dear Sir or Madam, I am writing to...', 'Hi, I wanted to ask you...'],
      2, '"Dear Sir or Madam, I am writing to..." is formal — no slang, full sentence, professional tone! ✉️'),
    grmQ('What is a COMPOUND ADJECTIVE and when is a HYPHEN needed?',
      ['Two adjectives — a hyphen is always needed', 'Two words used together as an adjective before a noun — a hyphen links them', 'Any adjective with a suffix', 'An adjective and an adverb — always hyphenated'],
      1, 'Compound adjectives before a noun use a hyphen: "blue-eyed girl". After the noun, no hyphen: "her eyes are blue"! 👁️'),
    grmQ('Which sentence uses the SUBJUNCTIVE after "it is essential"?',
      ['It is essential that he attends the meeting.', 'It is essential that he attend the meeting.', 'It is essential that he attended the meeting.', 'It is essential that he has attended.'],
      1, '"It is essential that he attend" — subjunctive uses the BASE form after formal phrases like "it is essential that"! 📋'),
    grmQ('Which correctly uses ELLIPSIS at the end of a sentence for SUSPENSE?',
      ['She crept closer...', 'She crept closer...!', 'She crept closer….', 'She crept closer …..'],
      0, 'Three dots (...) at the end create suspense or trail off. No additional punctuation is needed after! 😬'),
    grmQ('Which is the CORRECT use of a HYPHEN in a COMPOUND ADJECTIVE after the noun?',
      ['The solution was well-known.', 'The well known solution worked.', 'The solution well-known worked.', 'The solution was well known.'],
      3, 'After the noun, compound adjectives do NOT need a hyphen: "the solution was well known". Before: "a well-known solution". ✅'),
    grmQ('Which sentence uses FORMAL vocabulary?',
      ['The government wants to get rid of the rule.', 'The government intends to abolish the legislation.', 'The government reckons the rule is rubbish.', 'The government thinks the rule\'s not great.'],
      1, '"Intends to abolish the legislation" uses precise, formal vocabulary — perfect for reports and essays! 🏛️'),
    grmQ('What is the difference between ACTIVE and PASSIVE VOICE?',
      ['Active: subject receives the action; Passive: subject does the action', 'Active: subject does the action; Passive: subject receives the action', 'There is no real difference', 'Active is past tense; Passive is present tense'],
      1, 'Active: "The dog bit the man." (dog = doer). Passive: "The man was bitten by the dog." (man = receiver) 🔄'),
    grmQ('Which sentence uses a SEMI-COLON correctly between two related clauses?',
      ['She trained every day; she won the race.', 'She trained every day, she won the race.', 'She trained every day: she won the race.', 'She trained, every day; she won.'],
      0, 'Semi-colon between two independent clauses that are closely related: "trained every day; won the race." ✅🏅'),
    grmQ('Which is an example of the SUBJUNCTIVE MOOD in a formal request?',
      ['I demand that he stops immediately.', 'I demand that he stop immediately.', 'I demand that he stopped immediately.', 'I demand that he will stop immediately.'],
      1, '"Demand/request/insist that he STOP" — the subjunctive drops the -s and uses the base form! 📢'),
    grmQ('Which is a RELATIVE CLAUSE beginning with "whom"?',
      ['The teacher whom I respect retired last year.', 'The teacher who I respect retired last year.', 'The teacher which I respect retired.', 'The teacher whose respect retired.'],
      0, '"Whom" is the object form of "who" — used when the person is the object of the relative clause: "I respect him" → whom! 👩‍🏫'),
    grmQ('Which sentence uses PATHETIC FALLACY to show JOY?',
      ['It was raining on her birthday.', 'The sun beamed as she opened her presents.', 'There were clouds in the sky.', 'The weather was average.'],
      1, '"The sun beamed" reflects joy and happiness — that\'s pathetic fallacy using sunshine to show emotion! ☀️🎁'),
    grmQ('Which of these is a DISCOURSE MARKER for CONTRAST?',
      ['Furthermore', 'In addition', 'However', 'As a result'],
      2, '"However" signals contrast — it shows the next point disagrees with or differs from the previous one! 🔄'),
    grmQ('Which sentence uses a HYPHEN correctly to join a PREFIX?',
      ['re-enter the building', 'reenter the building', 're enter the building', 'reentering is needed'],
      0, 'When a prefix ends and the root word begins with the same vowel (re-enter), a hyphen is used! ✅'),
    grmQ('Which sentence uses FORMAL register correctly in an ARGUMENT?',
      ['I totally think more homework is rubbish.', 'It is widely argued that excessive homework is detrimental to well-being.', 'Too much homework is really bad for kids, obviously.', 'Homework — too much — is not good, I reckon.'],
      1, 'Formal argument uses impersonal language, hedging ("it is widely argued"), and precise vocabulary! 📜'),
    grmQ('Which is NOT a function of ELLIPSIS?',
      ['Creating suspense', 'Showing a trailing thought', 'Replacing a full stop in every sentence', 'Indicating missing words in a quotation'],
      2, 'Ellipsis is not a replacement for a full stop — it has specific rhetorical and editorial purposes! ✍️'),
    grmQ('Which sentence uses "whom" CORRECTLY?',
      ['Whom is calling?', 'To whom should I address this letter?', 'Whom went to the party?', 'Whom is the winner?'],
      1, '"Whom" is for the object of a verb or preposition: "I should address this to HIM" → "to whom". 📝'),
    grmQ('Which sentence uses a MODAL VERB to give ADVICE?',
      ['You must leave now or else.', 'You should eat more vegetables.', 'You can do whatever you want.', 'You will be fine.'],
      1, '"Should" gives gentle advice — it suggests what would be beneficial without being too forceful! 🥦'),
    grmQ('Which is the BEST example of SHORT SENTENCES used for DRAMATIC EFFECT?',
      ['After a very long time spent waiting and worrying, she finally heard the news.', 'She heard the news and then she was shocked.', 'After a long wait, she heard the news. She froze. Everything changed.', 'The news arrived eventually and she was shocked by it.'],
      2, '"She froze. Everything changed." — very short sentences after a longer one create powerful dramatic impact! ⚡'),
  ];
}

// ── Year 6 (Age 10–11) ──────────────────────────────────────
function grmYear6() {
  return [
    // ── Original 15 questions ──
    grmQ('Which sentence is in the ACTIVE VOICE?',
      ['The trophy was won by the team.', 'The team won the trophy.', 'The trophy, won by the team, gleamed.', 'Won by the team, the trophy gleamed.'],
      1, 'Active voice: subject (team) performs the action. Passive reverses this. Active is usually more direct! 🏆'),
    grmQ('Which correctly uses a SEMICOLON to join clauses?',
      ['The sun set; the stars appeared.', 'The sun set, the stars appeared.', 'The sun set: the stars appeared.', 'The sun set. The stars appeared;'],
      0, 'A semicolon joins two closely related independent clauses — stronger than a comma, weaker than a full stop! ⭐'),
    grmQ('Which sentence uses the SUBJUNCTIVE correctly?',
      ['I suggest that he goes home now.', 'I suggest that he go home now.', 'I suggest that he went home now.', 'I suggest that he will go home now.'],
      1, '"He go" — the subjunctive uses the base form (no -s/es). Used in formal suggestions and "if" clauses! 🎓'),
    grmQ('What is the effect of ANAPHORA (repeating words at the start of clauses)?',
      ['It makes the text harder to read', 'It creates rhythm and emphasis', 'It is always a grammatical error', 'It makes the text shorter'],
      1, 'Anaphora: "We shall fight... We shall never surrender." Repetition creates power and rhythm! ✊'),
    grmQ('Which sentence uses a COLON correctly for an explanation?',
      ['She was exhausted: she had run a marathon.', 'She was exhausted, she had run a marathon.', 'She was exhausted; she had run a marathon.', 'She was exhausted — she had run.'],
      0, 'The colon says "here\'s why": She was exhausted: the reason follows. ✅🏃'),
    grmQ('Which is an example of a COMPOUND-COMPLEX sentence?',
      ['The dog barked.', 'The dog barked and ran away.', 'Although it was dark, the dog barked and ran.', 'The dog that barked.'],
      2, 'Compound-complex: two+ independent clauses + one subordinate clause. "Although it was dark" (sub) + "barked and ran" (compound)! 🐕'),
    grmQ('Which uses a DASH for dramatic effect?',
      ['She opened the box — it was empty.', 'She opened the box, it was empty.', 'She opened the box: it was empty.', 'She opened the box. it was empty.'],
      0, 'A dash creates a dramatic pause before a surprising or important reveal! 📦'),
    grmQ('Which sentence CORRECTLY converts to the PASSIVE?',
      ['Active: "The artist painted the mural." → Passive: "The mural was painted by the artist."', 'Active: "The artist painted the mural." → Passive: "The mural painted the artist."', 'Active: "The artist painted the mural." → Passive: "The artist was painted by the mural."', 'Active: "The artist painted." → Passive: "The mural was painted."'],
      0, 'Passive: object (mural) → subject, verb → "was/were + past participle", agent follows "by"! 🎨'),
    grmQ('What is a PARENTHETICAL PHRASE?',
      ['The main clause of a sentence', 'Extra information inserted into a sentence using brackets, dashes, or commas', 'A phrase at the start of a sentence', 'A type of subordinate clause'],
      1, 'Parenthetical phrase: extra info that can be removed — (like this) — without changing the meaning! 📝'),
    grmQ('Which demonstrates VARYING SENTENCE LENGTH for effect?',
      ['She walked. She talked. She laughed. She sang.', 'She walked and talked and laughed and sang happily.', 'The morning was bright and cheerful. She skipped. It was perfect.', 'She walked to school happily every single morning.'],
      2, 'Mix long (descriptive) and short (punchy) sentences for rhythm and emphasis. "She skipped." stands out! ✍️'),
    grmQ('Which sentence contains a NOUN CLAUSE?',
      ['The tall building collapsed.', 'That she had won was unbelievable.', 'Running fast, she won.', 'The prize, which was big, gleamed.'],
      1, '"That she had won" acts as the subject of the sentence — a noun clause functions like a noun! 🏅'),
    grmQ('Which is CORRECT use of "who" vs "whom"?',
      ['Who did you speak to?', 'To whom did you speak?', 'Whom spoke to you?', 'Whom are you?'],
      1, '"Whom" is the object form. "To whom did you speak?" (you spoke TO HIM → whom). 🗣️'),
    grmQ('What does the word "discourse marker" mean?',
      ['A punctuation mark', 'A word or phrase that links ideas or organises text', 'A type of verb', 'A prefix or suffix'],
      1, 'Discourse markers organise and link ideas: "However", "Furthermore", "In contrast", "As a result"! 🔗'),
    grmQ('Which is an example of IRONY?',
      ['The sun is hot.', '"What a lovely day," she said, standing in the pouring rain.', 'She was very happy.', 'The dog ran quickly.'],
      1, 'Irony: saying the OPPOSITE of what you mean. "What a lovely day" in the rain is ironic! 😏'),
    grmQ('Which correctly punctuates a SENTENCE CONTAINING PARENTHESIS and direct speech?',
      ['"Help!" she cried (her voice shaking).', '"Help!" she cried (Her voice shaking).', '"Help!" she cried, (her voice shaking).', '"Help" she cried (her voice shaking)!'],
      0, 'Direct speech + brackets: "Help!" (exclamation inside speech) then (extra detail) in brackets. ✅'),

    // ── New questions ──
    grmQ('Which is a COMPOUND-COMPLEX sentence?',
      ['She laughed.', 'She laughed and cried.', 'Although she was nervous, she laughed and sang.', 'She was nervous and laughed.'],
      2, 'Compound-complex = at least two main clauses + one subordinate clause. "Although..." (subordinate) + two actions! ✅'),
    grmQ('Which sentence uses ANAPHORA?',
      ['She ran quickly and quietly.', 'We shall overcome. We shall persevere. We shall succeed.', 'The sun rose over the hills.', 'The bright, warm morning began.'],
      1, 'Anaphora repeats the same words at the start of successive clauses: "We shall... We shall... We shall..." for effect! ✊'),
    grmQ('What is a NOUN CLAUSE?',
      ['A clause that describes a noun', 'A clause that functions AS a noun (as subject or object)', 'A clause starting with a relative pronoun', 'A clause at the end of a sentence'],
      1, 'A noun clause acts like a noun: "What he said was wrong." "What he said" = the subject (a noun clause)! 📝'),
    grmQ('Which sentence uses "whom" CORRECTLY as an OBJECT?',
      ['Whom is your teacher?', 'The man whom I admire retired.', 'Whom did win the race?', 'Whom is speaking?'],
      1, '"Whom I admire" — "I admire HIM" → use "whom". Whom is always the object, never the subject! 👨‍🏫'),
    grmQ('Which is a DISCOURSE MARKER for ADDING a point?',
      ['However', 'Therefore', 'Furthermore', 'In contrast'],
      2, '"Furthermore" adds another point in the same direction: "Moreover", "In addition", "Furthermore"! 📋'),
    grmQ('Which is a DISCOURSE MARKER showing a RESULT?',
      ['However', 'On the other hand', 'As a result', 'In contrast'],
      2, '"As a result" signals that what follows is a consequence of what came before! 🔗'),
    grmQ('Which sentence demonstrates IRONY?',
      ['The sea is vast.', '"Oh brilliant," he groaned, as the rain started again.', 'She smiled when she won.', 'The flowers bloomed in spring.'],
      1, '"Oh brilliant," said with a groan in the rain = irony. The words mean the OPPOSITE of what is felt! 🌧️😒'),
    grmQ('Which is the CORRECT ACTIVE form of "The letter was written by her"?',
      ['The letter wrote her.', 'She wrote the letter.', 'The letter is written by her.', 'She was written the letter.'],
      1, 'Active: she (subject) + wrote (verb) + the letter (object). Simple, direct, clear! ✉️'),
    grmQ('What effect does ANAPHORA have in persuasive writing?',
      ['It makes the writing harder to understand', 'It creates rhythm and drives the argument home through repetition', 'It shows the writer has made an error', 'It always makes writing informal'],
      1, 'Repeating a phrase at the start of clauses builds momentum and makes the message more powerful! 📣'),
    grmQ('Which sentence uses a NOUN CLAUSE as the OBJECT?',
      ['I believe that honesty is the best policy.', 'Honesty is the best policy.', 'Running fast is good exercise.', 'The tall man arrived late.'],
      0, '"That honesty is the best policy" is the noun clause — it is the object of "believe"! ✅'),
    grmQ('Which sentence uses a PARENTHETICAL PHRASE with COMMAS?',
      ['The president, a former teacher, spoke passionately.', 'The president a former teacher spoke passionately.', 'The president spoke a former teacher passionately.', '(The president) a former teacher spoke passionately.'],
      0, 'Commas wrap the parenthetical phrase "a former teacher" — it adds info about the president without disrupting the sentence! 🎤'),
    grmQ('Which correctly identifies the PASSIVE in this sentence: "The painting was admired by everyone"?',
      ['The painting = agent; everyone = subject', 'Everyone = subject; admired = verb', 'The painting = subject receiving the action; everyone = agent', 'Admired = subject; everyone = object'],
      2, 'In passive: the painting (subject, receiver of action) was admired + by everyone (agent). ✅🖼️'),
    grmQ('Which is NOT a feature of FORMAL writing?',
      ['Complex sentences', 'Precise vocabulary', 'Colloquial phrases and slang', 'Impersonal language'],
      2, 'Formal writing avoids slang and colloquial phrases. It uses standard English and precise language! 📄'),
    grmQ('Which sentence uses a SEMI-COLON to link CONTRASTING ideas?',
      ['The days were long; the nights were short.', 'The days were long, the nights were short.', 'The days were long and the nights were short.', 'The days were long. The nights were short.'],
      0, 'A semi-colon links contrasting or closely related ideas: "long; short" — the contrast is elegant! ✅☀️🌙'),
    grmQ('Which sentence uses a COLON to introduce a QUOTATION?',
      ['She remembered his words: "Never give up."', 'She remembered his words, "Never give up."', 'She remembered his words; "Never give up."', 'She remembered his words — "Never give up."'],
      0, 'A colon introduces a quotation that directly follows and elaborates on the preceding clause! ✅💬'),
    grmQ('Which is a COMPOUND-COMPLEX sentence with the subordinate clause in the MIDDLE?',
      ['Although tired, she pushed on and finished the race.', 'She pushed on and finished the race.', 'She pushed on and finished, although tired.', 'She pushed on although tired.'],
      0, '"Although tired" (subordinate) is embedded at the start, followed by two main clause actions — compound-complex! 🏁'),
    grmQ('Which is an example of PARENTHESIS that adds the WRITER\'S VIEW?',
      ['The decision — arguably the wrong one — was made quickly.', 'The decision was made quickly.', 'The decision, quick, was made.', 'The decision was made (quickly).'],
      0, 'The dash parenthesis "arguably the wrong one" adds the writer\'s evaluative opinion — a powerful technique! ✍️'),
    grmQ('Which sentence uses a NOUN CLAUSE as the SUBJECT?',
      ['That she lied surprised everyone.', 'She lied and everyone was surprised.', 'Everyone was surprised.', 'She lied, which was surprising.'],
      0, '"That she lied" = noun clause acting as the grammatical subject of the sentence! ✅'),
    grmQ('Which sentence is the BEST example of SOPHISTICATED SENTENCE VARIETY?',
      ['She was happy. She won. She smiled.', 'After months of training, she crossed the finish line. She had won. Joy was written across her face.', 'She won the race and she was happy and she smiled.', 'She won the race after training for months and she was happy and she smiled.'],
      1, 'Varying sentence types (complex + short + minor) creates rhythm, emphasis, and shows mastery of structure! ✍️🏅'),
    grmQ('Which is a DISCOURSE MARKER showing CONCESSION?',
      ['Therefore', 'Furthermore', 'Admittedly', 'As a result'],
      2, '"Admittedly" concedes a point to strengthen the argument: "Admittedly, the plan has flaws, but..." 🤝'),
    grmQ('Which sentence uses the PASSIVE to OMIT the agent deliberately?',
      ['Mistakes were made.', 'I made mistakes.', 'She made mistakes and regretted them.', 'The mistakes I made were serious.'],
      0, '"Mistakes were made" is a classic passive — it deliberately hides WHO made them! Politicians love it! 😬'),
    grmQ('Which sentence uses "who" correctly (as SUBJECT)?',
      ['The girl who won the race is my sister.', 'The girl whom won the race is my sister.', 'The girl which won the race is my sister.', 'The girl whose won the race is my sister.'],
      0, '"Who won the race" — "who" is the subject of the relative clause (she won). Use "whom" only for objects! 🏃‍♀️'),
    grmQ('Which is an example of a MINOR SENTENCE used for effect?',
      ['She ran as fast as she could and eventually crossed the line.', 'Silence.', 'She ran to the finish.', 'The race had lasted two long hours.'],
      1, '"Silence." is a minor sentence — it has no verb but its abruptness creates powerful dramatic impact! 🤫'),
    grmQ('Which sentence uses IRONY to CRITICISE?',
      ['The service was slow and inefficient.', '"Oh, wonderful service," she muttered after waiting an hour.', 'She waited an hour and was annoyed.', 'The restaurant was busy that night.'],
      1, '"Oh, wonderful service" after waiting an hour = irony. The tone and context show the opposite is meant! 😒'),
    grmQ('Which is the CORRECT use of a COLON in a FORMAL piece?',
      ['There is one solution: hard work.', 'There is one solution, hard work.', 'There is one solution — hard work.', 'Hard work: there is one solution.'],
      0, 'The colon follows a complete clause and introduces the explanation or answer: "one solution: hard work." ✅💪'),
    grmQ('Which sentence uses a PARENTHETICAL PHRASE with DASHES to add CONTRAST?',
      ['The film — despite the mixed reviews — was genuinely moving.', 'The film was genuinely moving despite reviews.', 'Despite reviews, the film moving was.', 'The film was moving — despite reviews.'],
      0, 'The dashes isolate "despite the mixed reviews" as parenthetical — it adds a contrasting point dramatically! 🎬'),
    grmQ('Which correctly identifies ANAPHORA in a speech?',
      ['She used long sentences throughout.', 'She began each clause with "We will" to build momentum.', 'She varied her vocabulary to impress.', 'She used short sentences at the end.'],
      1, 'Anaphora = starting successive clauses with the same words. "We will..." "We will..." builds rhythm and power! 📣'),
    grmQ('Which sentence uses the SUBJUNCTIVE in a formal CONDITIONAL?',
      ['If she was here, she would help.', 'If she were here, she would help.', 'If she is here, she would help.', 'If she has been here, she would help.'],
      1, '"If she were here" — formal subjunctive uses "were" for ALL subjects in hypothetical conditions! 🎓'),
    grmQ('Which of these is the BEST example of a COMPLEX SENTENCE for an argument essay?',
      ['I think this is good.', 'This is good because many people agree.', 'Although critics argue otherwise, the evidence strongly suggests that regular exercise significantly improves mental health.', 'Regular exercise is good.'],
      2, 'A complex sentence with a concessive subordinate clause, formal vocabulary, and hedging = sophisticated argument writing! 📝'),
  ];
}
